# Generated by Django 5.1.15 on 2026-09-05 13:04

import apps.grading.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_committeemember_district_verified_and_more'),
        ('submissions', '0002_alter_submissionfile_av_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='punkty')),
                ('method', models.CharField(choices=[('CONSENSUS', 'zgodne oceny'), ('THIRD_REVIEW', 'trzeci recenzent'), ('MODERATION', 'posiedzenie komisji'), ('APPEAL', 'po reklamacji')], max_length=16, verbose_name='tryb ustalenia')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='rozstrzygnięta')),
                ('rationale', models.TextField(blank=True, verbose_name='uzasadnienie')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_grades', to=settings.AUTH_USER_MODEL, verbose_name='rozstrzygnął')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'ocena uzgodniona',
                'verbose_name_plural': 'oceny uzgodnione',
                'ordering': ('-decided_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField(default=1, verbose_name='runda')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='punkty')),
                ('comment_internal', models.TextField(blank=True, verbose_name='komentarz wewnętrzny')),
                ('comment_for_participant', models.TextField(blank=True, verbose_name='komentarz dla uczestnika')),
                ('annotations', models.JSONField(blank=True, default=apps.grading.models.default_annotations, verbose_name='adnotacje')),
                ('status', models.CharField(choices=[('ASSIGNED', 'przydzielona'), ('DRAFT', 'szkic'), ('SUBMITTED', 'wystawiona')], default='ASSIGNED', max_length=16, verbose_name='status')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='przydzielona')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='wystawiona')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='accounts.committeemember')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'recenzja',
                'verbose_name_plural': 'recenzje',
                'ordering': ('submission', 'round', 'id'),
                'constraints': [models.UniqueConstraint(fields=('submission', 'reviewer', 'round'), name='grading_review_unique_assignment'), models.CheckConstraint(condition=models.Q(('round__gte', 1)), name='grading_review_round_positive'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'SUBMITTED'), _negated=True), ('score__isnull', False), _connector='OR'), name='grading_review_submitted_has_score')],
            },
        ),
    ]
