# Generated by Django 5.1.15 on 2026-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'przydzielona'), ('DRAFT', 'szkic'), ('SUBMITTED', 'wystawiona'), ('CANCELLED', 'anulowana')], default='ASSIGNED', max_length=16, verbose_name='status'),
        ),
    ]
