# Generated by Django 5.1.15 on 2026-09-15 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Zależności zawężone do migracji, które faktycznie tworzą wskazywane modele (``CommitteeMember``
    # i ``Problem``), zamiast do czoła tamtych aplikacji, które dopisał autogenerator. Powód jest
    # praktyczny: testy migracji danych (``apps/accounts/tests/test_migrations.py``) przewijają
    # ``accounts`` wstecz, a każda migracja wisząca na czole tamtej aplikacji jedzie wtedy razem z nią.
    dependencies = [
        ('accounts', '0001_initial'),
        ('competitions', '0001_initial'),
        ('grading', '0002_alter_review_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReviewerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzona')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reviewer_rules', to=settings.AUTH_USER_MODEL, verbose_name='utworzył')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_rules', to='competitions.problem')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_rules', to='accounts.committeemember')),
            ],
            options={
                'verbose_name': 'reguła przydziału zadania',
                'verbose_name_plural': 'reguły przydziału zadań',
                'ordering': ('problem', 'created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('problem', 'reviewer'), name='grading_problem_rule_unique_reviewer')],
            },
        ),
    ]
