# Generated by Django 5.1.15 on 2026-09-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_problem_reviewer_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgrade',
            name='method',
            field=models.CharField(choices=[('CONSENSUS', 'zgodne oceny'), ('THIRD_REVIEW', 'trzeci recenzent'), ('MODERATION', 'posiedzenie komisji'), ('APPEAL', 'po reklamacji'), ('OVERRIDE', 'korekta koordynatora')], max_length=16, verbose_name='tryb ustalenia'),
        ),
    ]
