# Generated by Django 5.1.15 on 2026-09-16 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_supervisor_rbac_group'),
        ('competitions', '0015_school_supervisors_and_quality'),
        ('grading', '0007_rubric_notes_and_review_deadlines'),
        ('submissions', '0003_school_supervisors_and_quality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('text', models.TextField(max_length=2000, verbose_name='treść')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='kolejność')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_snippets', to='accounts.committeemember', verbose_name='właściciel')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_snippets', to='competitions.problem', verbose_name='zadanie')),
            ],
            options={
                'verbose_name': 'szablon komentarza',
                'verbose_name_plural': 'szablony komentarzy',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReviewWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='początek pracy')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ostatni sygnał')),
                ('seconds', models.PositiveIntegerField(default=0, verbose_name='zmierzony czas (s)')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_log', to='grading.review')),
            ],
            options={
                'verbose_name': 'czas pracy nad recenzją',
                'verbose_name_plural': 'czasy pracy nad recenzjami',
                'ordering': ('review', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('UNREADABLE', 'praca nieczytelna'), ('WRONG_PROBLEM', 'rozwiązanie innego zadania'), ('PLAGIARISM', 'podejrzenie niesamodzielności'), ('OTHER', 'inne')], max_length=24, verbose_name='rodzaj')),
                ('text', models.TextField(max_length=1000, verbose_name='opis')),
                ('status', models.CharField(choices=[('OPEN', 'otwarte'), ('RESOLVED', 'rozwiązane')], default='OPEN', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zgłoszone')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='rozwiązane')),
                ('resolution', models.TextField(blank=True, verbose_name='rozstrzygnięcie')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_work_issues', to=settings.AUTH_USER_MODEL, verbose_name='rozwiązał')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='grading.review')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_issues', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'zgłoszenie problemu z pracą',
                'verbose_name_plural': 'zgłoszenia problemów z pracami',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
