# Generated by Django 6.1.1 on 2026-10-04 17:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16, verbose_name='język')),
                ('key', models.CharField(max_length=64, verbose_name='klucz napisu')),
                ('msgctxt', models.TextField(blank=True, verbose_name='kontekst (msgctxt)')),
                ('msgid', models.TextField(verbose_name='napis źródłowy (msgid)')),
                ('plural_index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='forma mnoga')),
                ('text', models.TextField(verbose_name='proponowane tłumaczenie')),
                ('status', models.CharField(choices=[('pending', 'czeka'), ('approved', 'zatwierdzona'), ('rejected', 'odrzucona'), ('superseded', 'zastąpiona')], default='pending', max_length=16, verbose_name='stan')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zgłoszona')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='rozstrzygnięta')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_decisions', to=settings.AUTH_USER_MODEL, verbose_name='rozstrzygnął')),
            ],
            options={
                'verbose_name': 'propozycja tłumaczenia',
                'verbose_name_plural': 'propozycje tłumaczeń',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TranslationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16, verbose_name='język')),
                ('key', models.CharField(max_length=64, verbose_name='klucz napisu')),
                ('msgctxt', models.TextField(blank=True, verbose_name='kontekst (msgctxt)')),
                ('msgid', models.TextField(verbose_name='napis źródłowy (msgid)')),
                ('plural_index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='forma mnoga')),
                ('text', models.TextField(verbose_name='tłumaczenie')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zatwierdzone')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_overrides', to=settings.AUTH_USER_MODEL, verbose_name='zatwierdził')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='translation_review.translationsuggestion')),
            ],
            options={
                'verbose_name': 'zatwierdzone tłumaczenie',
                'verbose_name_plural': 'zatwierdzone tłumaczenia',
                'ordering': ('language', 'msgid'),
            },
        ),
        migrations.CreateModel(
            name='TranslationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='oddany')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='translation_review.translationsuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'głos na tłumaczenie',
                'verbose_name_plural': 'głosy na tłumaczenia',
            },
        ),
        migrations.CreateModel(
            name='TranslatorGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16, verbose_name='język')),
                ('level', models.CharField(choices=[('translator', 'tłumacz'), ('reviewer', 'recenzent tłumaczeń')], default='translator', max_length=16, verbose_name='poziom')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='nadane')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translator_grants_given', to=settings.AUTH_USER_MODEL, verbose_name='nadał')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translator_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uprawnienie tłumacza',
                'verbose_name_plural': 'uprawnienia tłumaczy',
                'ordering': ('language', 'user'),
            },
        ),
        migrations.CreateModel(
            name='TranslationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16, verbose_name='język')),
                ('page', models.CharField(blank=True, max_length=300, verbose_name='strona')),
                ('phrase', models.CharField(blank=True, max_length=300, verbose_name='napis na stronie')),
                ('comment', models.TextField(max_length=2000, verbose_name='uwaga')),
                ('status', models.CharField(choices=[('open', 'otwarte'), ('closed', 'zamknięte')], default='open', max_length=16, verbose_name='stan')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zgłoszone')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='zamknięte')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_reports_closed', to=settings.AUTH_USER_MODEL, verbose_name='zamknął')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'zgłoszenie tłumaczenia',
                'verbose_name_plural': 'zgłoszenia tłumaczeń',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['language', 'status'], name='translation_review_report_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='translationsuggestion',
            index=models.Index(fields=['language', 'key', 'status'], name='translation_review_sugg_idx'),
        ),
        migrations.AddConstraint(
            model_name='translationoverride',
            constraint=models.UniqueConstraint(fields=('language', 'key'), name='translation_review_override_unique'),
        ),
        migrations.AddConstraint(
            model_name='translationvote',
            constraint=models.UniqueConstraint(fields=('suggestion', 'user'), name='translation_review_vote_unique'),
        ),
        migrations.AddConstraint(
            model_name='translatorgrant',
            constraint=models.UniqueConstraint(fields=('user', 'language'), name='translation_review_grant_unique'),
        ),
    ]
