# Generated by Django 6.1.1 on 2026-10-04 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0014_merge_20261004_1935'),
        ('translation_review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='translatorgrant',
            name='translation_review_grant_unique',
        ),
        migrations.AddField(
            model_name='translationoverride',
            name='base_text',
            field=models.TextField(blank=True, verbose_name='tłumaczenie w katalogu przy decyzji'),
        ),
        migrations.AddField(
            model_name='translationoverride',
            name='kind',
            field=models.CharField(choices=[('change', 'poprawka'), ('confirmation', 'potwierdzenie')], default='change', max_length=16, verbose_name='rodzaj'),
        ),
        migrations.AddField(
            model_name='translatorgrant',
            name='competition',
            field=models.ForeignKey(blank=True, help_text='Puste = nadanie superkoordynatora (cała platforma).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator_grants', to='tenancy.competition', verbose_name='konkurs nadania'),
        ),
        migrations.AddConstraint(
            model_name='translatorgrant',
            constraint=models.UniqueConstraint(fields=('user', 'language', 'competition'), name='translation_review_grant_unique', nulls_distinct=False),
        ),
    ]
