# Generated by Django 5.1.15 on 2026-09-05 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_committeemember_district_verified_and_more'),
        ('submissions', '0002_alter_submissionfile_av_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='złożona')),
                ('argument', models.TextField(verbose_name='uzasadnienie')),
                ('status', models.CharField(choices=[('OPEN', 'złożona'), ('IN_REVIEW', 'rozpatrywana'), ('REJECTED', 'odrzucona'), ('ACCEPTED', 'uwzględniona'), ('PARTIALLY_ACCEPTED', 'częściowo uwzględniona')], default='OPEN', max_length=24, verbose_name='status')),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='accounts.participant')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'reklamacja',
                'verbose_name_plural': 'reklamacje',
                'ordering': ('filed_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AppealDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nowa punktacja')),
                ('justification', models.TextField(verbose_name='uzasadnienie')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='rozstrzygnięta')),
                ('appeal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='appeals.appeal')),
                ('committee', models.ManyToManyField(blank=True, related_name='appeal_decisions', to='accounts.committeemember', verbose_name='skład komisji')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_decisions', to=settings.AUTH_USER_MODEL, verbose_name='rozstrzygnął')),
            ],
            options={
                'verbose_name': 'decyzja o reklamacji',
                'verbose_name_plural': 'decyzje o reklamacjach',
                'ordering': ('-decided_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(fields=('submission', 'filed_by'), name='appeals_appeal_unique_participant'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(fields=('submission',), name='appeals_appeal_unique_submission'),
        ),
    ]
