# Generated by Django 5.1.15 on 2026-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rspo', models.PositiveIntegerField(unique=True, verbose_name='numer RSPO')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa')),
                ('kind', models.CharField(choices=[('LO', 'liceum ogólnokształcące'), ('TECHNIKUM', 'technikum'), ('BRANZOWA_1', 'branżowa szkoła I stopnia'), ('BRANZOWA_2', 'branżowa szkoła II stopnia'), ('ARTYSTYCZNA', 'szkoła artystyczna'), ('SPECJALNA', 'szkoła specjalna przysposabiająca do pracy'), ('INNA', 'inna')], default='INNA', max_length=16, verbose_name='typ')),
                ('voivodeship', models.CharField(choices=[('dolnoslaskie', 'dolnośląskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('lodzkie', 'łódzkie'), ('malopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('slaskie', 'śląskie'), ('swietokrzyskie', 'świętokrzyskie'), ('warminsko-mazurskie', 'warmińsko-mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=100, verbose_name='województwo')),
                ('city', models.CharField(max_length=120, verbose_name='miejscowość')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='kod pocztowy')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adres')),
                ('is_public', models.BooleanField(default=True, verbose_name='publiczna')),
                ('search_text', models.CharField(db_index=True, editable=False, max_length=400, verbose_name='tekst wyszukiwania')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywna')),
                ('source_year', models.CharField(default='2025/2026', max_length=9, verbose_name='rok wykazu')),
            ],
            options={
                'verbose_name': 'szkoła',
                'verbose_name_plural': 'szkoły',
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['voivodeship', 'search_text'], name='schools_voiv_search_idx')],
            },
        ),
    ]
