# Generated by Django 6.1.1 on 2026-09-24 16:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # ``submissions.0001_initial``, a nie najnowsza migracja prac (tak ją wpisał ``makemigrations``):
    # tabela ocen AI potrzebuje wyłącznie tabeli ``Submission`` (klucz obcy do ``pk``), a zależność
    # od ``0008`` cofała tę aplikację razem z każdym testem migracji prac (``submissions.0005``),
    # po czym ``Competition.objects.all().delete()`` sięgał kaskadą do nieistniejącej tabeli
    # ``ai_grading_aigradingsettings``. Zmiana przy scaleniu wydania v0.34.0, przed pierwszym
    # wdrożeniem tej migracji – na żadnej bazie nie jest jeszcze zastosowana.
    dependencies = [
        ('competitions', '0031_interview_score'),
        ('submissions', '0001_initial'),
        ('tenancy', '0008_competition_submission_forward_emails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiGradingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_encrypted', models.TextField(blank=True, verbose_name='klucz API (zaszyfrowany)')),
                ('api_key_last4', models.CharField(blank=True, max_length=4, verbose_name='ostatnie znaki klucza')),
                ('api_key_set_at', models.DateTimeField(blank=True, null=True, verbose_name='klucz ustawiony')),
                ('api_key_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='klucz sprawdzony')),
                ('api_key_check_ok', models.BooleanField(blank=True, null=True, verbose_name='klucz działa')),
                ('api_key_check_message', models.CharField(blank=True, max_length=300, verbose_name='wynik sprawdzenia')),
                ('model', models.CharField(choices=[('claude-opus-5', 'Claude Opus 5 (domyślny, dokładniejszy)'), ('claude-sonnet-5', 'Claude Sonnet 5 (tańszy)')], default='claude-opus-5', max_length=40, verbose_name='model')),
                ('spending_limit_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='limit wydatków (USD)')),
                ('total_calls', models.PositiveIntegerField(default=0, verbose_name='wywołań API')),
                ('total_input_tokens', models.PositiveBigIntegerField(default=0, verbose_name='tokeny wejścia')),
                ('total_output_tokens', models.PositiveBigIntegerField(default=0, verbose_name='tokeny wyjścia')),
                ('total_cache_write_tokens', models.PositiveBigIntegerField(default=0, verbose_name='tokeny zapisu cache')),
                ('total_cache_read_tokens', models.PositiveBigIntegerField(default=0, verbose_name='tokeny odczytu cache')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12, verbose_name='szacowany koszt (USD)')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmienione')),
                ('api_key_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='klucz ustawił')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grading_settings', to='tenancy.competition', verbose_name='konkurs')),
            ],
            options={
                'verbose_name': 'ustawienia oceny AI',
                'verbose_name_plural': 'ustawienia oceny AI',
            },
        ),
        migrations.CreateModel(
            name='AiStageVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_to_participants', models.BooleanField(default=False, verbose_name='pokaż uczestnikom ocenę AI')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmienione')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='zmienił')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_visibility', to='competitions.stage', verbose_name='etap')),
            ],
            options={
                'verbose_name': 'widoczność oceny AI',
                'verbose_name_plural': 'widoczność oceny AI',
            },
        ),
        migrations.CreateModel(
            name='AiAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'oczekuje'), ('RUNNING', 'w toku'), ('DONE', 'gotowa'), ('ERROR', 'błąd')], default='PENDING', max_length=16, verbose_name='status')),
                ('model', models.CharField(blank=True, max_length=60, verbose_name='model')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zlecona')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='przekazana do kolejki')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='rozpoczęta')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='przekazana do Anthropic')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='zakończona')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='próby')),
                ('proposed_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='proponowane punkty')),
                ('max_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='maksimum')),
                ('criteria', models.JSONField(blank=True, default=list, verbose_name='kryteria')),
                ('summary', models.TextField(blank=True, verbose_name='podsumowanie')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='błędy w pracy')),
                ('confidence', models.CharField(blank=True, choices=[('niska', 'niska'), ('średnia', 'średnia'), ('wysoka', 'wysoka')], max_length=16, verbose_name='pewność')),
                ('injection_suspected', models.BooleanField(default=False, verbose_name='podejrzenie próby manipulacji')),
                ('error_code', models.CharField(blank=True, max_length=32, verbose_name='kod błędu')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='błąd')),
                ('request_id', models.CharField(blank=True, max_length=80, verbose_name='identyfikator żądania')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='tokeny wejścia')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='tokeny wyjścia')),
                ('cache_write_tokens', models.PositiveIntegerField(default=0, verbose_name='tokeny zapisu cache')),
                ('cache_read_tokens', models.PositiveIntegerField(default=0, verbose_name='tokeny odczytu cache')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='szacowany koszt (USD)')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='zlecił')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessment', to='submissions.submission', verbose_name='praca')),
            ],
            options={
                'verbose_name': 'ocena AI',
                'verbose_name_plural': 'oceny AI',
                'ordering': ('submission_id',),
                'indexes': [models.Index(fields=['status', 'dispatched_at'], name='ai_assessment_queue_idx')],
            },
        ),
    ]
