# Generated by Django 6.1.1 on 2026-09-26 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, help_text='Pozycja pojawia się także w pasku u góry okna po przewinięciu strony (jak „Zadania”, „Harmonogram”, „Warsztaty”, „Kontakt”).', verbose_name='w przyklejonym pasku')),
                ('expand', models.BooleanField(default=False, help_text='Podstrony tej strony pokazują się w menu jako lista rozwijana (jak „Dokumenty”).', verbose_name='lista rozwijana')),
                ('promote', models.BooleanField(default=False, help_text='Podstrona listy rozwijanej, która stoi w menu jako osobna pozycja – zaraz po stronie głównej – i znika z listy (jak „Komitety”).', verbose_name='wyniesiona do menu głównego')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'verbose_name': 'ustawienia menu',
                'verbose_name_plural': 'ustawienia menu',
            },
        ),
    ]
