# Generated by Django 6.1.1 on 2026-09-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_key', models.CharField(db_index=True, max_length=64, verbose_name='skrót pary (IP, login)')),
                ('user_key', models.CharField(db_index=True, max_length=64, verbose_name='skrót loginu')),
                ('at', models.FloatField(db_index=True, verbose_name='chwila próby (sekundy od epoki)')),
            ],
            options={
                'verbose_name': 'nieudana próba logowania',
                'verbose_name_plural': 'nieudane próby logowania',
            },
        ),
    ]
