# Generated by Django 6.1.1 on 2026-09-26 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
        ('dj_pages', '0002_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_id', models.PositiveIntegerField(blank=True, help_text='Edycja w systemie zawodów: stąd biorą się linki do tabel wyników.', null=True, verbose_name='edycja')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.pagecontent')),
            ],
            options={
                'verbose_name': 'edycja w archiwum',
                'verbose_name_plural': 'edycje w archiwum',
            },
        ),
        migrations.CreateModel(
            name='DocumentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(blank=True, max_length=50, verbose_name='wersja')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='data dokumentu')),
                ('status_label', models.CharField(blank=True, help_text='Np. „Projekt do zatwierdzenia uchwałą Zarządu”.', max_length=200, verbose_name='status')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.pagecontent')),
            ],
            options={
                'verbose_name': 'metryka dokumentu',
                'verbose_name_plural': 'metryki dokumentów',
            },
        ),
        migrations.CreateModel(
            name='NewsMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data publikacji')),
                ('lead', models.TextField(blank=True, max_length=500, verbose_name='lead')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.pagecontent')),
            ],
            options={
                'verbose_name': 'metryka aktualności',
                'verbose_name_plural': 'metryki aktualności',
            },
        ),
    ]
