# Generated by Django 6.1.1 on 2026-09-23 17:08

import apps.competitions.storage
import apps.promo.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0008_competition_submission_forward_emails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='tytuł')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='opis')),
                ('file', models.FileField(max_length=255, storage=apps.competitions.storage.private_media_storage, upload_to=apps.promo.models.material_upload_to, verbose_name='plik')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'JPG'), ('png', 'PNG')], max_length=4, verbose_name='format')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='rozmiar (B)')),
                ('preview', models.FileField(blank=True, max_length=255, upload_to=apps.promo.models.preview_upload_to, verbose_name='podgląd')),
                ('preview_is_generated', models.BooleanField(default=False, verbose_name='podgląd wygenerowany')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
                ('is_published', models.BooleanField(default=False, verbose_name='opublikowany')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='zarchiwizowany')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniony')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_materials', to='tenancy.competition', verbose_name='konkurs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='dodał')),
            ],
            options={
                'verbose_name': 'plakat do pobrania',
                'verbose_name_plural': 'plakaty do pobrania',
                'ordering': ('competition', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PromoDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='pobrano')),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='pseudonim adresu IP')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_downloads', to='tenancy.competition', verbose_name='konkurs')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='promo.promomaterial', verbose_name='plakat')),
            ],
            options={
                'verbose_name': 'pobranie plakatu',
                'verbose_name_plural': 'pobrania plakatów',
                'ordering': ('-downloaded_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='promomaterial',
            index=models.Index(fields=['competition', 'is_published', 'position'], name='promo_material_listing'),
        ),
        migrations.AddIndex(
            model_name='promodownload',
            index=models.Index(fields=['competition', 'downloaded_at'], name='promo_download_stats'),
        ),
        migrations.AddIndex(
            model_name='promodownload',
            index=models.Index(fields=['material', 'downloaded_at'], name='promo_download_material'),
        ),
    ]
