# Generated by Django 6.1.1 on 2026-09-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promomaterial',
            name='group',
            field=models.CharField(blank=True, max_length=100, verbose_name='karta (grupa)'),
        ),
        migrations.AddField(
            model_name='promomaterial',
            name='variant_label',
            field=models.CharField(blank=True, max_length=60, verbose_name='wariant (przycisk)'),
        ),
    ]
