"""Zamrożona przynależność wpisów do grup przy publikacji wyników (STAT-01, poprawka M3).

Nowa tabela bez danych – wiersze dopisuje odbiornik publikacji albo leniwe zamrożenie. Odwracalna.
"""
# Generated by Django 6.1.1 on 2026-10-04 18:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0033_video_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(default='school', max_length=16, verbose_name='oś')),
                ('entry_pk', models.BigIntegerField(verbose_name='wpis')),
                ('group_key', models.CharField(blank=True, max_length=300, verbose_name='klucz grupy')),
                ('group_label', models.CharField(blank=True, max_length=255, verbose_name='podpis grupy')),
                ('group_city', models.CharField(blank=True, max_length=120, verbose_name='miejscowość grupy')),
                ('school_id', models.IntegerField(blank=True, null=True, verbose_name='szkoła z wykazu')),
                ('rspo', models.IntegerField(blank=True, null=True, verbose_name='RSPO')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region')),
                ('qualified', models.BooleanField(default=False, verbose_name='zakwalifikowany')),
                ('has_submission', models.BooleanField(default=False, verbose_name='praca oddana')),
                ('has_late', models.BooleanField(default=False, verbose_name='praca po terminie')),
                ('frozen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zamrożono')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='competitions.stage', verbose_name='etap')),
            ],
            options={
                'verbose_name': 'zamrożona przynależność wpisu',
                'verbose_name_plural': 'zamrożone przynależności wpisów',
                'indexes': [models.Index(fields=['entry_pk'], name='school_stats_frozen_entry_idx')],
                'constraints': [models.UniqueConstraint(fields=('axis', 'stage', 'entry_pk'), name='school_stats_frozen_unique')],
            },
        ),
    ]
