# Generated by Django 6.1.1 on 2026-10-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='adres e-mail (małe litery)')),
                ('undeliverable_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='twarde odbicie od')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='powód (diagnoza serwera)')),
                ('status_code', models.CharField(blank=True, max_length=16, verbose_name='kod stanu (RFC 3463)')),
                ('source', models.CharField(blank=True, choices=[('smtp', 'odmowa relaya'), ('dsn', 'zawiadomienie o niedoręczeniu')], max_length=8, verbose_name='źródło')),
                ('hard_bounces', models.PositiveIntegerField(default=0, verbose_name='twarde odbicia')),
                ('soft_bounces', models.PositiveIntegerField(default=0, verbose_name='miękkie odbicia')),
                ('last_soft_bounce_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatnie miękkie odbicie')),
                ('last_soft_reason', models.CharField(blank=True, max_length=500, verbose_name='powód ostatniego miękkiego odbicia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='ostatnie zdarzenie')),
            ],
            options={
                'verbose_name': 'stan doręczalności adresu',
                'verbose_name_plural': 'stany doręczalności adresów',
                'ordering': ('-undeliverable_at', 'email'),
            },
        ),
    ]
