# Generated by Django 5.1.15 on 2026-09-17 14:11

import apps.tenancy.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='identyfikator')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('short_name', models.CharField(blank=True, max_length=60, verbose_name='nazwa skrócona')),
                ('genitive_name', models.CharField(blank=True, max_length=200, verbose_name='nazwa w dopełniaczu')),
                ('locative_name', models.CharField(blank=True, max_length=200, verbose_name='nazwa w miejscowniku')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='hasło')),
                ('accent_colour', models.CharField(blank=True, max_length=7, validators=[apps.tenancy.models.validate_hex_colour], verbose_name='kolor akcentu')),
                ('organizer_name', models.CharField(max_length=200, verbose_name='organizator')),
                ('organizer_address', models.CharField(blank=True, max_length=200, verbose_name='adres')),
                ('organizer_registry', models.CharField(blank=True, max_length=200, verbose_name='dane rejestrowe')),
                ('organizer_url', models.URLField(blank=True, verbose_name='strona organizatora')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail kontaktowy')),
                ('contact_phone', models.CharField(blank=True, max_length=40, verbose_name='telefon')),
                ('dpo_email', models.EmailField(blank=True, max_length=254, verbose_name='inspektor ochrony danych')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='nadawca listów')),
                ('email_subject_prefix', models.CharField(blank=True, max_length=60, verbose_name='prefiks tematu')),
                ('routing_mode', models.CharField(choices=[('DOMAIN', 'własna domena'), ('PATH', 'prefiks ścieżki na domenie platformy')], default='DOMAIN', max_length=8, verbose_name='tryb adresowania')),
                ('primary_domain', models.CharField(blank=True, max_length=255, verbose_name='domena główna')),
                ('path_prefix', models.SlugField(blank=True, max_length=40, verbose_name='prefiks ścieżki')),
                ('default_language', models.CharField(default='pl', max_length=8, verbose_name='język domyślny')),
                ('time_zone', models.CharField(default='Europe/Warsaw', max_length=64, verbose_name='strefa czasowa')),
                ('feature_flags', models.JSONField(blank=True, default=dict, verbose_name='przełączniki')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='favikona')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logotyp')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='competition', to='wagtailcore.site', verbose_name='witryna')),
            ],
            options={
                'verbose_name': 'konkurs',
                'verbose_name_plural': 'konkursy',
                'ordering': ('name', 'id'),
            },
        ),
    ]
