# Generated by Django 6.1.1 on 2026-10-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0012_competition_site_logo_social_image'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='theme_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='opcje motywu'),
        ),
        migrations.AddField(
            model_name='competition',
            name='theme_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='themes.themeversion', verbose_name='motyw (wersja)'),
        ),
    ]
