# Generated by Django 6.1.1 on 2026-10-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0013_competition_registration_mode'),
        ('tenancy', '0013_competition_theme_options_competition_theme_version'),
    ]

    operations = [
    ]
