# Generated by Django 6.1.1 on 2026-10-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0016_merge_visa_invitation_award_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='kind',
            field=models.CharField(choices=[('LAUREAT', 'dyplom laureata'), ('FINALISTA', 'dyplom finalisty'), ('UCZESTNIK', 'zaświadczenie uczestnika'), ('OPIEKUN', 'zaświadczenie opiekuna'), ('WARSZTATY', 'zaświadczenie z warsztatów'), ('GUARDIAN_FORM', 'wzór zgody opiekuna'), ('INVOICE', 'faktura / rachunek'), ('ATTENDANCE_LIST', 'lista obecności'), ('STUDENT_STATUS', 'zaświadczenie o statusie ucznia'), ('VISA_INVITATION', 'list zapraszający (wiza)'), ('MEDAL_GOLD', 'dyplom – złoty medal'), ('MEDAL_SILVER', 'dyplom – srebrny medal'), ('MEDAL_BRONZE', 'dyplom – brązowy medal'), ('HON_MENTION', 'dyplom – wyróżnienie')], max_length=24, verbose_name='rodzaj'),
        ),
    ]
