# Generated by Django 6.1.1 on 2026-10-04 15:32

import apps.competitions.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='identyfikator')),
                ('name', models.CharField(max_length=80, verbose_name='nazwa')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='autor')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='wbudowany')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
            ],
            options={
                'verbose_name': 'motyw',
                'verbose_name_plural': 'motywy',
                'ordering': ('-is_builtin', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ThemeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, verbose_name='wersja')),
                ('status', models.CharField(choices=[('valid', 'poprawna'), ('invalid', 'odrzucona')], max_length=10, verbose_name='stan')),
                ('package', models.FileField(blank=True, storage=apps.competitions.storage.private_media_storage, upload_to='themes/', verbose_name='paczka')),
                ('package_sha256', models.CharField(max_length=64, verbose_name='SHA-256 paczki')),
                ('package_size', models.PositiveIntegerField(default=0, verbose_name='rozmiar paczki')),
                ('public_prefix', models.CharField(blank=True, max_length=200, verbose_name='prefiks publiczny')),
                ('manifest', models.JSONField(default=dict, verbose_name='manifest')),
                ('tokens', models.JSONField(default=dict, verbose_name='tokeny')),
                ('templates', models.JSONField(default=dict, verbose_name='szablony')),
                ('files', models.JSONField(default=list, verbose_name='pliki')),
                ('report', models.JSONField(default=dict, verbose_name='raport walidacji')),
                ('has_screenshot', models.BooleanField(default=False, verbose_name='zrzut ekranu')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='wgrano')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='themes.theme', verbose_name='motyw')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='wgrał')),
            ],
            options={
                'verbose_name': 'wersja motywu',
                'verbose_name_plural': 'wersje motywów',
                'ordering': ('theme__name', '-uploaded_at'),
                'constraints': [models.UniqueConstraint(fields=('theme', 'version'), name='themes_version_unique')],
            },
        ),
    ]
