# Generated by Django 6.1.1 on 2026-10-04 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0014_merge_20261004_1935'),
        ('themes', '0002_classic_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, verbose_name='pozycje')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='rewizja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zapisano')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_menu', to='tenancy.competition', verbose_name='konkurs')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='zapisał')),
            ],
            options={
                'verbose_name': 'menu serwisu',
                'verbose_name_plural': 'menu serwisów',
            },
        ),
        migrations.CreateModel(
            name='ThemeCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(default=dict, verbose_name='opcje')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zapisano')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_customizations', to='tenancy.competition', verbose_name='konkurs')),
                ('theme_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='themes.themeversion', verbose_name='wersja motywu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='zapisał')),
            ],
            options={
                'verbose_name': 'dostosowanie motywu',
                'verbose_name_plural': 'dostosowania motywów',
                'constraints': [models.UniqueConstraint(fields=('competition', 'theme_version'), name='themes_customization_unique')],
            },
        ),
    ]
