# Generated by Django 5.1.15 on 2026-09-05 13:04

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='akcja')),
                ('target_type', models.CharField(max_length=64, verbose_name='typ obiektu')),
                ('target_id', models.CharField(max_length=64, verbose_name='id obiektu')),
                ('diff', models.JSONField(blank=True, default=apps.core.models.default_diff, verbose_name='zmiana')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adres IP')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='kiedy')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='wykonawca')),
            ],
            options={
                'verbose_name': 'wpis audytu',
                'verbose_name_plural': 'wpisy audytu',
                'ordering': ('-at', '-id'),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='core_audit_target_idx')],
            },
        ),
    ]
