# Generated by Django 6.1.1 on 2026-10-04 17:01

import apps.webinars.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0033_video_room'),
        ('tenancy', '0012_competition_site_logo_social_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True, verbose_name='identyfikator zdarzenia')),
                ('event', models.CharField(max_length=40, verbose_name='zdarzenie')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='odebrane')),
            ],
            options={
                'verbose_name': 'zdarzenie LiveKit',
                'verbose_name_plural': 'zdarzenia LiveKit',
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='opis')),
                ('starts_at', models.DateTimeField(verbose_name='początek')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='czas trwania (min)')),
                ('audience', models.CharField(choices=[('competition', 'wszyscy uczestnicy konkursu'), ('edition', 'uczestnicy bieżącej edycji'), ('stage', 'uczestnicy wybranego etapu'), ('committee', 'komisja (recenzenci i komisja odwoławcza)'), ('captains', 'kapitanowie drużyn bieżącej edycji')], default='edition', max_length=16, verbose_name='odbiorcy')),
                ('include_committee', models.BooleanField(default=False, verbose_name='także komisja')),
                ('public_link', models.BooleanField(default=False, verbose_name='link dla gości bez konta')),
                ('public_key', models.CharField(default=apps.webinars.models.new_public_key, max_length=64, unique=True, verbose_name='klucz linku dla gości')),
                ('record', models.BooleanField(default=False, verbose_name='nagrywanie')),
                ('email_reminder', models.BooleanField(default=False, verbose_name='przypomnienie e-mailem')),
                ('room_key', models.CharField(default=apps.webinars.models.new_room_key, max_length=32, unique=True, verbose_name='końcówka nazwy pokoju')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='założony')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniony')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='rozpoczęty')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='zakończony')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='odwołany')),
                ('announced_at', models.DateTimeField(blank=True, null=True, verbose_name='zaproszenie wysłane')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='przypomnienie wysłane')),
                ('live_started_at', models.DateTimeField(blank=True, null=True, verbose_name='pokój aktywny od')),
                ('live_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='pokój zamknięty')),
                ('stream_egress_id', models.CharField(blank=True, max_length=64, verbose_name='transmisja (egress)')),
                ('co_moderators', models.ManyToManyField(blank=True, related_name='webinars_co_moderated', to=settings.AUTH_USER_MODEL, verbose_name='współprowadzący')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to='tenancy.competition', verbose_name='konkurs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars_created', to=settings.AUTH_USER_MODEL, verbose_name='założył')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars', to='competitions.stage', verbose_name='etap')),
            ],
            options={
                'verbose_name': 'webinar',
                'verbose_name_plural': 'webinary',
                'ordering': ('starts_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WebinarAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=64, verbose_name='identyfikator w pokoju')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='nazwa w pokoju')),
                ('role', models.CharField(choices=[('presenter', 'prowadzący'), ('viewer', 'widz'), ('guest', 'gość')], default='viewer', max_length=16, verbose_name='rola')),
                ('first_token_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='pierwszy token')),
                ('first_joined_at', models.DateTimeField(blank=True, null=True, verbose_name='pierwsze wejście')),
                ('last_joined_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatnie wejście')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='wyjście')),
                ('seconds', models.PositiveIntegerField(default=0, verbose_name='czas obecności (s)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinar_attendances', to=settings.AUTH_USER_MODEL, verbose_name='konto')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='webinars.webinar', verbose_name='webinar')),
            ],
            options={
                'verbose_name': 'uczestnik webinaru',
                'verbose_name_plural': 'uczestnicy webinaru',
                'ordering': ('webinar', 'first_token_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WebinarNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_webinar', models.BooleanField(default=True, verbose_name='listy o webinarach')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmienione')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='konto')),
            ],
            options={
                'verbose_name': 'ustawienia powiadomień o webinarach',
                'verbose_name_plural': 'ustawienia powiadomień o webinarach',
            },
        ),
        migrations.CreateModel(
            name='WebinarRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egress_id', models.CharField(max_length=64, unique=True, verbose_name='egress')),
                ('status', models.CharField(choices=[('active', 'nagrywa'), ('complete', 'gotowe'), ('failed', 'błąd')], default='active', max_length=16, verbose_name='stan')),
                ('storage_key', models.CharField(max_length=255, verbose_name='plik')),
                ('size', models.BigIntegerField(blank=True, null=True, verbose_name='rozmiar (B)')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='długość (s)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='początek')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='koniec')),
                ('published', models.BooleanField(default=False, verbose_name='opublikowane')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='opublikowane')),
                ('error', models.CharField(blank=True, max_length=200, verbose_name='błąd')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='włączył')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='webinars.webinar', verbose_name='webinar')),
            ],
            options={
                'verbose_name': 'nagranie webinaru',
                'verbose_name_plural': 'nagrania webinarów',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['competition', 'starts_at'], name='webinars_comp_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='webinarattendee',
            constraint=models.UniqueConstraint(fields=('webinar', 'identity'), name='webinars_attendee_unique_identity'),
        ),
    ]
