# Generated by Django 6.1.1 on 2026-10-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarattendee',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='usunięty z pokoju'),
        ),
    ]
