# Generated by Django 6.1.1 on 2026-09-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SsoNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'zużyty token SSO',
                'verbose_name_plural': 'zużyte tokeny SSO',
            },
        ),
        migrations.CreateModel(
            name='CompetitionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('routing_mode', models.CharField(choices=[('DOMAIN', 'własny host'), ('PATH', 'prefiks ścieżki')], default='DOMAIN', max_length=8)),
                ('path_prefix', models.SlugField(blank=True, max_length=40)),
                ('hosts_path_prefixes', models.BooleanField(default=False)),
                ('public_origin', models.CharField(blank=True, max_length=255)),
                ('public_path_prefix', models.CharField(blank=True, max_length=41)),
                ('linked_paths', models.JSONField(blank=True, default=list)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('content_imported_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='competition', to='sites.site')),
            ],
            options={
                'verbose_name': 'witryna konkursu',
                'verbose_name_plural': 'witryny konkursów',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='CompetitionHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, unique=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='dj_sites.competitionsite')),
            ],
            options={
                'verbose_name': 'host konkursu',
                'verbose_name_plural': 'hosty konkursów',
                'ordering': ('host',),
            },
        ),
        migrations.AddConstraint(
            model_name='competitionsite',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='dj_sites_single_default_competition'),
        ),
    ]
