# Generated by Django 6.1.1 on 2026-10-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dj_sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionsite",
            name="starter_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
