# Generated by Django 5.1.15 on 2026-09-08 13:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_sitesettings_organizer_logo_alter_contentpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("image", 3),
                    ("document", 6),
                    ("embed", 7),
                    ("heading", 12),
                    ("notice", 15),
                    ("definitions", 22),
                    ("schedule", 32),
                    ("stage_timeline", 34),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "blockquote",
                            ],
                            "label": "akapit",
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "obraz"}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "podpis", "max_length": 250, "required": False},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("image", 1), ("caption", 2)]], {}),
                    4: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "dokument"}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "etykieta linku", "max_length": 250, "required": False},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("document", 4), ("label", 5)]], {}),
                    7: ("wagtail.embeds.blocks.EmbedBlock", (), {"label": "osadzenie (film, prezentacja)"}),
                    8: ("wagtail.blocks.CharBlock", (), {"label": "tekst", "max_length": 250}),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("2", "rozdział (H2)"), ("3", "paragraf (H3)")], "label": "poziom"},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Fragment adresu po „#”, np. „rozdzial-3”. Zmiana psuje istniejące odnośniki.",
                            "label": "kotwica",
                            "max_length": 100,
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "pokaż w spisie rozdziałów", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 8), ("level", 9), ("anchor", 10), ("in_toc", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "informacja"), ("warning", "ostrzeżenie")], "label": "ton"},
                    ),
                    14: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "blockquote",
                            ],
                            "label": "treść",
                        },
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("tone", 13), ("text", 14)]], {}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "nagłówek etykiet", "max_length": 100, "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "nagłówek wartości", "max_length": 100, "required": False},
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"label": "etykieta", "max_length": 500}),
                    19: ("wagtail.blocks.CharBlock", (), {"label": "wartość", "max_length": 1000}),
                    20: ("wagtail.blocks.StructBlock", [[("term", 18), ("description", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {"label": "pary"}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("term_label", 16), ("description_label", 17), ("rows", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "podpis tabeli", "max_length": 250, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "nagłówek kolumny „temat”", "max_length": 100, "required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "nagłówek kolumny „termin”", "max_length": 100, "required": False},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "nagłówek kolumny „godziny”", "max_length": 100, "required": False},
                    ),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "temat", "max_length": 250}),
                    28: ("wagtail.blocks.CharBlock", (), {"label": "termin", "max_length": 100}),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "godziny", "max_length": 100, "required": False},
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("topic", 27), ("date", 28), ("time", 29)]], {}),
                    31: ("wagtail.blocks.ListBlock", (30,), {"label": "wiersze"}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("caption", 23),
                                ("topic_label", 24),
                                ("date_label", 25),
                                ("time_label", 26),
                                ("rows", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Puste = sama tabela terminów, bez nagłówka.",
                            "label": "nagłówek sekcji",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("heading", 33)]], {}),
                },
                verbose_name="treść",
            ),
        ),
        migrations.AlterField(
            model_name="documentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("image", 3),
                    ("document", 6),
                    ("embed", 7),
                    ("heading", 12),
                    ("notice", 15),
                    ("definitions", 22),
                    ("schedule", 32),
                    ("stage_timeline", 34),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "blockquote",
                            ],
                            "label": "akapit",
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "obraz"}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "podpis", "max_length": 250, "required": False},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("image", 1), ("caption", 2)]], {}),
                    4: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"label": "dokument"}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "etykieta linku", "max_length": 250, "required": False},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("document", 4), ("label", 5)]], {}),
                    7: ("wagtail.embeds.blocks.EmbedBlock", (), {"label": "osadzenie (film, prezentacja)"}),
                    8: ("wagtail.blocks.CharBlock", (), {"label": "tekst", "max_length": 250}),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("2", "rozdział (H2)"), ("3", "paragraf (H3)")], "label": "poziom"},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Fragment adresu po „#”, np. „rozdzial-3”. Zmiana psuje istniejące odnośniki.",
                            "label": "kotwica",
                            "max_length": 100,
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "pokaż w spisie rozdziałów", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 8), ("level", 9), ("anchor", 10), ("in_toc", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "informacja"), ("warning", "ostrzeżenie")], "label": "ton"},
                    ),
                    14: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "blockquote",
                            ],
                            "label": "treść",
                        },
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("tone", 13), ("text", 14)]], {}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "nagłówek etykiet", "max_length": 100, "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "nagłówek wartości", "max_length": 100, "required": False},
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"label": "etykieta", "max_length": 500}),
                    19: ("wagtail.blocks.CharBlock", (), {"label": "wartość", "max_length": 1000}),
                    20: ("wagtail.blocks.StructBlock", [[("term", 18), ("description", 19)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {"label": "pary"}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("term_label", 16), ("description_label", 17), ("rows", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "podpis tabeli", "max_length": 250, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "nagłówek kolumny „temat”", "max_length": 100, "required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "nagłówek kolumny „termin”", "max_length": 100, "required": False},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "nagłówek kolumny „godziny”", "max_length": 100, "required": False},
                    ),
                    27: ("wagtail.blocks.CharBlock", (), {"label": "temat", "max_length": 250}),
                    28: ("wagtail.blocks.CharBlock", (), {"label": "termin", "max_length": 100}),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "godziny", "max_length": 100, "required": False},
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("topic", 27), ("date", 28), ("time", 29)]], {}),
                    31: ("wagtail.blocks.ListBlock", (30,), {"label": "wiersze"}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("caption", 23),
                                ("topic_label", 24),
                                ("date_label", 25),
                                ("time_label", 26),
                                ("rows", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Puste = sama tabela terminów, bez nagłówka.",
                            "label": "nagłówek sekcji",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("heading", 33)]], {}),
                },
                verbose_name="treść",
            ),
        ),
    ]
