# Generated by Django 5.1.15 on 2026-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0014_site_social_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="tiktok_url",
            field=models.URLField(
                blank=True,
                default="https://www.tiktok.com/@olimpiadakwantowa",
                verbose_name="X (dawniej Twitter)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                default="https://www.youtube.com/@OlimpiadaKwantowa",
                verbose_name="X (dawniej Twitter)",
            ),
        ),
    ]
