# Generated by Django 5.1.15 on 2026-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_certificate_templates_and_workshop_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='supervisor_registration_enabled',
            field=models.BooleanField(default=False, help_text='Wyłączone: adres /register/supervisor/ zwraca 404, nigdzie nie ma do niego odnośnika, a uczestnicy nie widzą w profilu pola z adresem opiekuna szkolnego. Opiekunowie, którzy mają już konto, zachowują swój panel.', verbose_name='rejestracja opiekunów szkolnych'),
        ),
    ]
