# Generated by Django 6.1.1 on 2026-09-22 21:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_sponsor_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='supervisor_registration_intro',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Puste = nad formularzem /register/supervisor/ nie ma żadnego tekstu.', verbose_name='wstęp nad formularzem rejestracji opiekunów'),
        ),
    ]
