# Generated by Django 6.1.1 on 2026-09-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0027_supervisor_registration_intro"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditingFreeze",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="zamrożone")),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="Pierwsze zdanie banera w /cms/. Puste = tekst domyślny.",
                        max_length=500,
                        verbose_name="komunikat na banerze",
                    ),
                ),
                ("changed_at", models.DateTimeField(blank=True, null=True, verbose_name="zmieniono")),
                ("changed_by", models.CharField(blank=True, max_length=150, verbose_name="zmienił")),
            ],
            options={
                "verbose_name": "zamrożenie edycji stron",
                "verbose_name_plural": "zamrożenie edycji stron",
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("id", 1)), name="cms_editing_freeze_singleton")
                ],
            },
        ),
    ]
