# Generated by Django 6.1.1 on 2026-09-28 09:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_home_hero_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('poster', 8), ('image', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Np. „Olimpiada Kwantowa 2026/2027”.', 'label': 'nadtytuł', 'max_length': 60, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Krótko – 2–4 słowa, np. „Rozpoczęliśmy rejestrację!”.', 'label': 'hasło plakatu', 'max_length': 80}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'tekst', 'max_length': 240, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Krótki napis w kółku, np. „udział bezpłatny” albo data.', 'label': 'pieczątka', 'max_length': 30, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'napis na przycisku', 'max_length': 40, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Adres w serwisie (np. /register/) albo pełny adres https://…', 'label': 'adres przycisku', 'max_length': 300, 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('czerwony', 'czerwony plakat na granacie'), ('granatowy', 'granatowy plakat z czerwonym akcentem'), ('papier', 'jasny papier z czerwonym nadrukiem')], 'label': 'kolorystyka'}), 7: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Plakat znika sam, gdy okno rejestracji bieżącej edycji jest zamknięte albo jeszcze się nie zaczęło – np. dla „Rozpoczęliśmy rejestrację!”.', 'label': 'tylko przy otwartej rejestracji', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('kicker', 0), ('title', 1), ('text', 2), ('stamp', 3), ('button_label', 4), ('button_url', 5), ('theme', 6), ('registration_only', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'JPG, PNG albo WebP z biblioteki obrazów. Najlepiej poziomy, ok. 1600×700 px – obraz pokazuje się w całości, bez przycinania.', 'label': 'obraz'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Co widać i co jest napisane na obrazie – czyta to czytnik ekranu.', 'label': 'opis obrazu', 'max_length': 250}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Opcjonalnie: adres w serwisie (np. /register/) albo pełny adres https://…', 'label': 'adres po kliknięciu', 'max_length': 300, 'required': False}), 12: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Obraz znika sam, gdy okno rejestracji bieżącej edycji jest zamknięte.', 'label': 'tylko przy otwartej rejestracji', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('image', 9), ('alt', 10), ('link_url', 11), ('registration_only', 12)]], {})}, verbose_name='plakaty w sliderze'),
        ),
    ]
