# Generated by Django 6.1.1 on 2026-09-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_hero_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_show_intro',
            field=models.BooleanField(default=True, help_text='Plansza z nagłówkiem, wprowadzeniem i przyciskami „Zarejestruj się / Zaloguj się”. Wyłączona wraca sama, gdy slider nie ma żadnej innej planszy.', verbose_name='plansza z hasłem w sliderze'),
        ),
    ]
