# Generated by Django 6.1.1 on 2026-10-04 17:46

import apps.proctoring.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0035_committee_video_room_issuer'),
        ('competitions', '0033_video_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('coordinator', 'koordynator'), ('committee', 'komisja'), ('leader', 'opiekun drużyny')], max_length=16, verbose_name='rola')),
                ('delegation_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='delegacja')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='przydzielony')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to='competitions.stage', verbose_name='etap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to=settings.AUTH_USER_MODEL, verbose_name='konto')),
            ],
            options={
                'verbose_name': 'nadzorujący',
                'verbose_name_plural': 'nadzorujący',
                'ordering': ('stage', 'kind', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProctoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='nadzór włączony')),
                ('require_screen_share', models.BooleanField(default=False, verbose_name='wymagane udostępnienie ekranu')),
                ('require_microphone', models.BooleanField(default=False, verbose_name='wymagany mikrofon')),
                ('id_photo', models.CharField(choices=[('off', 'nie zbieramy'), ('optional', 'opcjonalne'), ('required', 'wymagane')], default='off', max_length=16, verbose_name='zdjęcie dokumentu')),
                ('record', models.BooleanField(default=False, verbose_name='nagrywanie kamer')),
                ('on_unavailable', models.CharField(choices=[('allow', 'uczeń pracuje, sesja dostaje znacznik „bez nadzoru”'), ('block', 'treść etapu zamknięta do decyzji koordynatora')], default='allow', max_length=8, verbose_name='gdy LiveKit nie działa')),
                ('instructions', models.TextField(blank=True, max_length=1000, verbose_name='dodatkowe instrukcje dla uczniów')),
                ('room_key', models.CharField(default=apps.proctoring.models.new_room_key, max_length=32, unique=True, verbose_name='końcówka nazw pokoi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmienione')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring', to='competitions.stage', verbose_name='etap')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nadzór etapu',
                'verbose_name_plural': 'nadzór etapów',
            },
        ),
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(db_index=True, max_length=32, verbose_name='identyfikator w pokoju')),
                ('group', models.CharField(default='m', max_length=24, verbose_name='grupa')),
                ('check_result', models.JSONField(blank=True, default=dict, verbose_name='wynik sprawdzenia')),
                ('check_passed_at', models.DateTimeField(blank=True, null=True, verbose_name='sprzęt sprawdzony')),
                ('id_photo_key', models.CharField(blank=True, max_length=255, verbose_name='zdjęcie dokumentu (klucz)')),
                ('id_photo_at', models.DateTimeField(blank=True, null=True, verbose_name='zdjęcie dokumentu')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='nadzór rozpoczęty')),
                ('unproctored_at', models.DateTimeField(blank=True, null=True, verbose_name='bez nadzoru od')),
                ('connected', models.BooleanField(default=False, verbose_name='połączony')),
                ('camera_live', models.BooleanField(default=False, verbose_name='kamera nadaje')),
                ('screen_live', models.BooleanField(default=False, verbose_name='ekran udostępniony')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatni sygnał')),
                ('attendance', models.CharField(choices=[('unknown', 'nie odnotowano'), ('present', 'obecny'), ('absent', 'nieobecny')], default='unknown', max_length=8, verbose_name='obecność')),
                ('attendance_at', models.DateTimeField(blank=True, null=True, verbose_name='obecność odnotowana')),
                ('alternative_status', models.CharField(blank=True, choices=[('', 'brak'), ('requested', 'prośba'), ('approved', 'zatwierdzona'), ('rejected', 'odrzucona')], default='', max_length=12, verbose_name='alternatywa')),
                ('alternative_reason', models.CharField(blank=True, choices=[('no_camera', 'brak kamery'), ('camera_broken', 'kamera nie działa'), ('no_browser', 'przeglądarka nie obsługuje nadzoru'), ('accessibility', 'potrzeby dostępności'), ('other', 'inny powód')], max_length=16, verbose_name='powód')),
                ('alternative_note', models.CharField(blank=True, max_length=300, verbose_name='uwaga ucznia')),
                ('alternative_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='prośba z')),
                ('alternative_decision', models.CharField(blank=True, max_length=300, verbose_name='ustalenie')),
                ('alternative_decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decyzja z')),
                ('hold_reason', models.CharField(blank=True, max_length=200, verbose_name='wstrzymanie usunięcia')),
                ('purged_at', models.DateTimeField(blank=True, null=True, verbose_name='nośniki usunięte')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='założona')),
                ('alternative_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attendance_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_sessions', to='accounts.participant', verbose_name='uczestnik')),
                ('proctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='proctoring.proctorassignment', verbose_name='nadzorujący')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_sessions', to='competitions.stage', verbose_name='etap')),
            ],
            options={
                'verbose_name': 'sesja nadzoru',
                'verbose_name_plural': 'sesje nadzoru',
                'ordering': ('stage', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProctoringRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egress_id', models.CharField(max_length=64, unique=True, verbose_name='egress')),
                ('track_sid', models.CharField(max_length=64, verbose_name='ścieżka')),
                ('status', models.CharField(choices=[('active', 'nagrywa'), ('complete', 'gotowe'), ('failed', 'błąd')], default='active', max_length=10, verbose_name='stan')),
                ('storage_key', models.CharField(max_length=255, verbose_name='plik')),
                ('size', models.BigIntegerField(blank=True, null=True, verbose_name='rozmiar (B)')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='długość (s)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='początek')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='koniec')),
                ('error', models.CharField(blank=True, max_length=200, verbose_name='błąd')),
                ('purged_at', models.DateTimeField(blank=True, null=True, verbose_name='usunięte')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='proctoring.proctoringsession')),
            ],
            options={
                'verbose_name': 'nagranie nadzoru',
                'verbose_name_plural': 'nagrania nadzoru',
                'ordering': ('started_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProctoringMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'wiadomość'), ('show_room', 'prośba: pokaż pokój'), ('show_id', 'prośba: pokaż dokument')], default='text', max_length=12, verbose_name='rodzaj')),
                ('body', models.CharField(blank=True, max_length=500, verbose_name='treść')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='wysłana')),
                ('via_data_channel', models.BooleanField(default=False, verbose_name='kanałem danych')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='potwierdzona')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='proctoring.proctoringsession')),
            ],
            options={
                'verbose_name': 'wiadomość nadzoru',
                'verbose_name_plural': 'wiadomości nadzoru',
                'ordering': ('sent_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProctoringIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='czas zdarzenia')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zgłoszony')),
                ('category', models.CharField(choices=[('absent', 'uczeń poza kadrem'), ('other_person', 'inna osoba w kadrze'), ('device', 'inne urządzenie'), ('communication', 'rozmowa lub komunikacja'), ('materials', 'niedozwolone materiały'), ('screen', 'ekran'), ('technical', 'problem techniczny'), ('other', 'inne')], max_length=16, verbose_name='kategoria')),
                ('severity', models.CharField(choices=[('info', 'informacja'), ('warning', 'ostrzeżenie'), ('serious', 'poważny')], default='warning', max_length=8, verbose_name='waga')),
                ('note', models.TextField(blank=True, max_length=2000, verbose_name='notatka')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='proctoring.proctoringsession')),
            ],
            options={
                'verbose_name': 'incydent nadzoru',
                'verbose_name_plural': 'incydenty nadzoru',
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('check_passed', 'sprzęt sprawdzony'), ('check_failed', 'sprawdzenie nieudane'), ('consent_given', 'zgoda wyrażona'), ('consent_withdrawn', 'zgoda wycofana'), ('id_photo', 'zdjęcie dokumentu'), ('started', 'nadawanie potwierdzone'), ('unproctored', 'praca bez nadzoru'), ('connected', 'połączenie'), ('disconnected', 'rozłączenie'), ('camera_on', 'kamera nadaje'), ('camera_off', 'kamera przestała nadawać'), ('screen_on', 'ekran udostępniony'), ('screen_off', 'udostępnianie ekranu zakończone'), ('stream_dropped', 'zerwany strumień (zgłoszenie przeglądarki)'), ('reconnected', 'ponowne połączenie (zgłoszenie przeglądarki)'), ('livekit_unavailable', 'serwer nadzoru niedostępny'), ('message', 'wiadomość nadzorującego'), ('message_seen', 'wiadomość potwierdzona'), ('attendance', 'obecność'), ('incident', 'incydent'), ('alternative', 'alternatywa'), ('recording', 'nagranie')], max_length=24, verbose_name='rodzaj')),
                ('source', models.CharField(choices=[('client', 'przeglądarka ucznia'), ('webhook', 'serwer LiveKit'), ('proctor', 'nadzorujący'), ('system', 'platforma')], max_length=8, verbose_name='źródło')),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='czas')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='szczegóły')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proctoring.proctoringsession')),
            ],
            options={
                'verbose_name': 'zdarzenie nadzoru',
                'verbose_name_plural': 'zdarzenia nadzoru',
                'ordering': ('at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProctoringConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64, verbose_name='wersja')),
                ('text_sha256', models.CharField(max_length=64, verbose_name='skrót treści')),
                ('given_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='wyrażona')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adres IP')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='wycofana')),
                ('guardian_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.consentrecord')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='proctoring.proctoringsession')),
            ],
            options={
                'verbose_name': 'zgoda na nadzór',
                'verbose_name_plural': 'zgody na nadzór',
                'ordering': ('-given_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='proctorassignment',
            constraint=models.UniqueConstraint(fields=('stage', 'user'), name='proctoring_assignment_unique_user'),
        ),
        migrations.AddIndex(
            model_name='proctoringsession',
            index=models.Index(fields=['stage', 'group'], name='proctoring_session_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='proctoringsession',
            constraint=models.UniqueConstraint(fields=('stage', 'participant'), name='proctoring_session_unique_participant'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(fields=['session', 'at'], name='proctoring_event_session_idx'),
        ),
    ]
