# Generated by Django 6.1.1 on 2026-10-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringconsent',
            name='guardian_statement',
            field=models.BooleanField(default=False, verbose_name='oświadczenie o zgodzie opiekuna na nadzór'),
        ),
        migrations.AddField(
            model_name='proctoringconsent',
            name='terms',
            field=models.JSONField(blank=True, default=dict, verbose_name='ustawienia etapu w chwili zgody'),
        ),
        migrations.AddField(
            model_name='proctoringsession',
            name='unproctored_reason',
            field=models.CharField(blank=True, max_length=24, verbose_name='powód pracy bez nadzoru'),
        ),
        migrations.AlterField(
            model_name='proctoringconfig',
            name='on_unavailable',
            field=models.CharField(choices=[('allow', 'pozwól pracować przy awarii serwera nadzoru (sesja ze znacznikiem)'), ('block', 'zamknij treść etapu do decyzji koordynatora')], default='block', max_length=8, verbose_name='gdy LiveKit nie działa'),
        ),
        migrations.AlterField(
            model_name='proctoringevent',
            name='kind',
            field=models.CharField(choices=[('check_passed', 'sprzęt sprawdzony'), ('check_failed', 'sprawdzenie nieudane'), ('consent_given', 'zgoda wyrażona'), ('consent_withdrawn', 'zgoda wycofana'), ('id_photo', 'zdjęcie dokumentu'), ('started', 'nadawanie potwierdzone'), ('unproctored', 'praca bez nadzoru'), ('connected', 'połączenie'), ('disconnected', 'rozłączenie'), ('camera_on', 'kamera nadaje'), ('camera_off', 'kamera przestała nadawać'), ('screen_on', 'ekran udostępniony'), ('screen_off', 'udostępnianie ekranu zakończone'), ('stream_dropped', 'zerwany strumień (zgłoszenie przeglądarki)'), ('connect_failed', 'nieudane połączenie (zgłoszenie przeglądarki)'), ('reconnected', 'ponowne połączenie (zgłoszenie przeglądarki)'), ('livekit_unavailable', 'serwer nadzoru niedostępny'), ('message', 'wiadomość nadzorującego'), ('message_seen', 'wiadomość potwierdzona'), ('attendance', 'obecność'), ('incident', 'incydent'), ('alternative', 'alternatywa'), ('recording', 'nagranie')], max_length=24, verbose_name='rodzaj'),
        ),
    ]
