# Generated by Django 6.1.1 on 2026-10-04 21:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def fill_account_identity(apps, schema_editor):
    """Pseudonim konta dla istniejących sesji – ta sama funkcja, co w pokoju rozmowy (WEB-01)."""
    from apps.webinars.services import pseudonym

    Session = apps.get_model("proctoring", "ProctoringSession")  # noqa: N806
    for session in Session.objects.select_related("participant__user").filter(account_identity=""):
        Session.objects.filter(pk=session.pk).update(account_identity=pseudonym(session.participant.user))


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0034_video_provider_livekit'),
        ('proctoring', '0002_review_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='account_identity',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='pseudonim konta'),
        ),
        migrations.CreateModel(
            name='InterviewRoomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=32, verbose_name='identyfikator w pokoju')),
                ('kind', models.CharField(choices=[('removed', 'usunięty z pokoju'), ('muted', 'bez głosu')], max_length=8, verbose_name='decyzja')),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='osoba')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='od')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_blocks', to='competitions.interviewslot', verbose_name='termin')),
            ],
            options={
                'verbose_name': 'decyzja moderatora rozmowy',
                'verbose_name_plural': 'decyzje moderatorów rozmów',
                'constraints': [models.UniqueConstraint(fields=('slot', 'identity'), name='proctoring_room_block_unique')],
            },
        ),
        migrations.RunPython(fill_account_identity, migrations.RunPython.noop),
    ]
