# Generated by Django 6.1.1 on 2026-10-04 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0037_team_leader_rbac_group'),
        ('competitions', '0033_video_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=64, verbose_name='strefa czasowa')),
                ('set_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ustawiono')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_zone_setting', to='accounts.region', verbose_name='kraj')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'strefa czasowa kraju',
                'verbose_name_plural': 'strefy czasowe krajów',
            },
        ),
        migrations.CreateModel(
            name='ParticipantTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=64, verbose_name='strefa czasowa')),
                ('set_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ustawiono')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_zone_setting', to='accounts.participant', verbose_name='uczestnik')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'strefa czasowa ucznia',
                'verbose_name_plural': 'strefy czasowe uczniów',
            },
        ),
        migrations.CreateModel(
            name='WindowPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='czas pracy (min)')),
                ('preferred_local_hour', models.PositiveSmallIntegerField(default=10, verbose_name='preferowana godzina startu')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmieniony')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='window_plan', to='competitions.stage', verbose_name='etap')),
            ],
            options={
                'verbose_name': 'plan okien etapu',
                'verbose_name_plural': 'plany okien etapów',
            },
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=16, verbose_name='oznaczenie')),
                ('starts_at', models.DateTimeField(verbose_name='start')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='time_windows.windowplan')),
            ],
            options={
                'verbose_name': 'okno czasowe',
                'verbose_name_plural': 'okna czasowe',
                'ordering': ('starts_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ParticipantWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_minutes', models.PositiveIntegerField(default=0, verbose_name='dodatkowy czas (min)')),
                ('reason', models.CharField(max_length=300, verbose_name='powód')),
                ('set_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ustawiono')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_windows', to='accounts.participant', verbose_name='uczestnik')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participant_assignments', to='time_windows.timewindow')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_windows', to='time_windows.windowplan')),
            ],
            options={
                'verbose_name': 'wyjątek ucznia w oknach',
                'verbose_name_plural': 'wyjątki uczniów w oknach',
            },
        ),
        migrations.CreateModel(
            name='DelegationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='przydzielono')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_windows', to='accounts.delegation', verbose_name='delegacja')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegation_assignments', to='time_windows.timewindow')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_windows', to='time_windows.windowplan')),
            ],
            options={
                'verbose_name': 'przydział delegacji do okna',
                'verbose_name_plural': 'przydziały delegacji do okien',
            },
        ),
        migrations.AddConstraint(
            model_name='windowplan',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 15), ('duration_minutes__lte', 1440)), name='time_windows_plan_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='windowplan',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_local_hour__lte', 23)), name='time_windows_plan_hour_range'),
        ),
        migrations.AddConstraint(
            model_name='timewindow',
            constraint=models.UniqueConstraint(fields=('plan', 'label'), name='time_windows_window_unique_label'),
        ),
        migrations.AddConstraint(
            model_name='timewindow',
            constraint=models.UniqueConstraint(fields=('plan', 'starts_at'), name='time_windows_window_unique_start'),
        ),
        migrations.AddConstraint(
            model_name='participantwindow',
            constraint=models.UniqueConstraint(fields=('plan', 'participant'), name='time_windows_participant_unique'),
        ),
        migrations.AddConstraint(
            model_name='participantwindow',
            constraint=models.CheckConstraint(condition=models.Q(('extra_minutes__lte', 1440)), name='time_windows_participant_extra_range'),
        ),
        migrations.AddConstraint(
            model_name='participantwindow',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='time_windows_participant_reason'),
        ),
        migrations.AddConstraint(
            model_name='delegationwindow',
            constraint=models.UniqueConstraint(fields=('plan', 'delegation'), name='time_windows_delegation_unique'),
        ),
    ]
