# Generated by Django 6.1.1 on 2026-10-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_windows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationwindow',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='delegation_assignments', to='time_windows.timewindow'),
        ),
        migrations.AlterField(
            model_name='participantwindow',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='participant_assignments', to='time_windows.timewindow'),
        ),
    ]
