# Generated by Django 6.1.1 on 2026-10-04 17:16

import apps.competitions.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0037_team_leader_rbac_group'),
        ('competitions', '0033_video_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_md', models.TextField(blank=True, max_length=100000, verbose_name='treść oficjalna (Markdown)')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='wersja')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='odcisk wersji')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmieniona')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation_source', to='competitions.problem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wersja oficjalna zadania',
                'verbose_name_plural': 'wersje oficjalne zadań',
            },
        ),
        migrations.CreateModel(
            name='StudentLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='język')),
                ('set_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ustawiony')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation_language', to='accounts.participant')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'język ucznia',
                'verbose_name_plural': 'języki uczniów',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16, verbose_name='język')),
                ('kind', models.CharField(choices=[('TEXT', 'tekst (Markdown)'), ('PDF', 'plik PDF')], default='TEXT', max_length=8, verbose_name='rodzaj')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='tytuł')),
                ('body_md', models.TextField(blank=True, max_length=100000, verbose_name='treść (Markdown)')),
                ('pdf', models.FileField(blank=True, storage=apps.competitions.storage.private_media_storage, upload_to='problems/translations/', verbose_name='plik PDF')),
                ('pdf_sha256', models.CharField(blank=True, max_length=64, verbose_name='sha256 pliku')),
                ('status', models.CharField(choices=[('DRAFT', 'szkic'), ('SUBMITTED', 'czeka na akceptację'), ('RETURNED', 'zwrócone do poprawy'), ('APPROVED', 'zatwierdzone')], default='DRAFT', max_length=16, verbose_name='stan')),
                ('source_version', models.PositiveIntegerField(default=1, verbose_name='wersja źródła')),
                ('outdated_since', models.DateTimeField(blank=True, null=True, verbose_name='nieaktualne od')),
                ('review_comment', models.TextField(blank=True, max_length=4000, verbose_name='komentarz komisji')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzone')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmienione')),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_translations', to='accounts.delegation')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='competitions.problem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tłumaczenie zadania',
                'verbose_name_plural': 'tłumaczenia zadań',
                'ordering': ('problem', 'language', 'delegation_id'),
            },
        ),
        migrations.CreateModel(
            name='TranslationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='wersja')),
                ('kind', models.CharField(choices=[('TEXT', 'tekst (Markdown)'), ('PDF', 'plik PDF')], max_length=8, verbose_name='rodzaj')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='tytuł')),
                ('body_md', models.TextField(blank=True, verbose_name='treść (Markdown)')),
                ('pdf', models.FileField(blank=True, max_length=300, storage=apps.competitions.storage.private_media_storage, upload_to='', verbose_name='plik PDF')),
                ('pdf_sha256', models.CharField(blank=True, max_length=64, verbose_name='sha256 pliku')),
                ('source_version', models.PositiveIntegerField(verbose_name='wersja źródła')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='wysłana')),
                ('decision', models.CharField(blank=True, choices=[('APPROVED', 'zatwierdzona'), ('RETURNED', 'zwrócona'), ('WITHDRAWN', 'wycofana')], max_length=16, verbose_name='decyzja')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decyzja z')),
                ('comment', models.TextField(blank=True, verbose_name='komentarz')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='problem_translations.translation')),
            ],
            options={
                'verbose_name': 'wersja tłumaczenia',
                'verbose_name_plural': 'wersje tłumaczeń',
                'ordering': ('translation', '-number'),
            },
        ),
        migrations.AddField(
            model_name='translation',
            name='approved_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='problem_translations.translationrevision'),
        ),
        migrations.CreateModel(
            name='TranslationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens_at', models.DateTimeField(verbose_name='otwarcie okna')),
                ('closes_at', models.DateTimeField(verbose_name='zamknięcie okna')),
                ('sharing_mode', models.CharField(choices=[('SEPARATE', 'osobne – każda delegacja tłumaczy sama'), ('SHARED', 'wspólne – jedno tłumaczenie na język')], default='SEPARATE', max_length=16, verbose_name='tłumaczenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmienione')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation_window', to='competitions.stage', verbose_name='etap')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'okno tłumaczeń',
                'verbose_name_plural': 'okna tłumaczeń',
            },
        ),
        migrations.CreateModel(
            name='DelegationLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='język')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='kolejność')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zadeklarowany')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_languages', to='accounts.delegation')),
            ],
            options={
                'verbose_name': 'język delegacji',
                'verbose_name_plural': 'języki delegacji',
                'ordering': ('delegation', 'position'),
                'constraints': [models.UniqueConstraint(fields=('delegation', 'code'), name='problem_translations_language_once'), models.UniqueConstraint(fields=('delegation', 'position'), name='problem_translations_language_position'), models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 2)), name='problem_translations_language_position_range')],
            },
        ),
        migrations.CreateModel(
            name='SourceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='wersja')),
                ('title', models.CharField(max_length=300, verbose_name='tytuł')),
                ('body_md', models.TextField(blank=True, verbose_name='treść (Markdown)')),
                ('pdf_name', models.CharField(blank=True, max_length=300, verbose_name='plik PDF')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzona')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='problem_translations.problemsource')),
            ],
            options={
                'verbose_name': 'wersja źródła',
                'verbose_name_plural': 'wersje źródła',
                'ordering': ('source', 'version'),
                'constraints': [models.UniqueConstraint(fields=('source', 'version'), name='problem_translations_source_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='translationrevision',
            constraint=models.UniqueConstraint(fields=('translation', 'number'), name='problem_translations_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(condition=models.Q(('delegation__isnull', False)), fields=('problem', 'language', 'delegation'), name='problem_translations_one_per_delegation'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(condition=models.Q(('delegation__isnull', True)), fields=('problem', 'language'), name='problem_translations_one_shared'),
        ),
        migrations.AddConstraint(
            model_name='translationwindow',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at__lt', models.F('closes_at'))), name='problem_translations_window_ordered'),
        ),
    ]
