# Generated by Django 6.1.1 on 2026-10-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcerevision',
            name='pdf_en_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='plik PDF (EN)'),
        ),
        migrations.AddField(
            model_name='sourcerevision',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='tytuł (EN)'),
        ),
        migrations.AddField(
            model_name='translation',
            name='edit_version',
            field=models.PositiveIntegerField(default=0, verbose_name='licznik zapisów'),
        ),
    ]
