# Generated by Django 6.1.1 on 2026-09-26 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('closed_notice', models.TextField(blank=True, help_text='Wyświetlany, dopóki etap się nie rozpocznie. Puste = komunikat systemowy.', max_length=500, verbose_name='komunikat przed otwarciem etapu')),
            ],
            options={
                'verbose_name': 'zadania etapu (z systemu)',
                'verbose_name_plural': 'zadania etapu (z systemu)',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='StageTimeline',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(blank=True, help_text='Puste = same karty etapów, bez nagłówka. Wariant „strona główna” ma własny nagłówek z edycją.', max_length=200, verbose_name='nagłówek sekcji')),
                ('variant', models.CharField(choices=[('block', 'w treści strony (karty etapów)'), ('home', 'strona główna („Przebieg zawodów”)')], default='block', max_length=8, verbose_name='wariant')),
            ],
            options={
                'verbose_name': 'terminy etapów (z systemu)',
                'verbose_name_plural': 'terminy etapów (z systemu)',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
