# Generated by Django 6.1.1 on 2026-09-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
        ('dj_live', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopSchedule',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('part', models.CharField(choices=[('schedule', 'harmonogram warsztatów (tabele)'), ('intro', 'wprowadzenie strony „Warsztaty”')], default='schedule', max_length=10, verbose_name='część strony')),
            ],
            options={
                'verbose_name': 'warsztaty (z systemu)',
                'verbose_name_plural': 'warsztaty (z systemu)',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
