"""Lista państw dla konkursu dzielącego uczestników na **kraje** (docs/tasks/REG-01.md § 1.3).

Zakres: wszystkie 193 państwa członkowskie ONZ, dwaj obserwatorzy (Stolica Apostolska, Palestyna)
oraz Tajwan, Kosowo, Hongkong i Makau – terytoria, z których uczniowie realnie startują
w olimpiadach międzynarodowych i które mają własne delegacje. Lista jest **zamknięta i w kodzie**,
a nie pobierana z biblioteki (``pycountry``, ``django-countries``): jedna zależność mniej, a zbiór
zmienia się raz na dekadę – nowe państwo dopisuje się tu jedną linią.

Kod regionu to **mała** litera alfa-2 ISO 3166-1 (``de``, ``us``, ``pl``), bo ``Region.code`` jest
slugiem trafiającym do adresów, filtrów i eksportów, a regiony startowe mają kody małymi literami.
Kosowo nie ma kodu ISO – ``xk`` jest kodem tymczasowym używanym przez Komisję Europejską i bank
światowy, i tylko taki ma sens w tabeli wyników.

Nazwy są **angielskie** (krótkie nazwy zwyczajowe, nie ustrojowe – „Germany”, a nie „Federal
Republic of Germany”): konkurs, dla którego powstała ta lista (``iqo``), jest anglojęzyczny, a nazwa
regionu jest daną konkursu, którą organizator może poprawić w ekranie „Regiony”. Tłumaczenia nazw
krajów na jedenaście języków interfejsu to osobna sprawa (dane, nie napisy interfejsu).
"""

from __future__ import annotations

#: ``(kod, nazwa)`` – w kolejności alfabetycznej nazw angielskich, w której trafiają do ``position``.
COUNTRIES: tuple[tuple[str, str], ...] = (
    ("af", "Afghanistan"),
    ("al", "Albania"),
    ("dz", "Algeria"),
    ("ad", "Andorra"),
    ("ao", "Angola"),
    ("ag", "Antigua and Barbuda"),
    ("ar", "Argentina"),
    ("am", "Armenia"),
    ("au", "Australia"),
    ("at", "Austria"),
    ("az", "Azerbaijan"),
    ("bs", "Bahamas"),
    ("bh", "Bahrain"),
    ("bd", "Bangladesh"),
    ("bb", "Barbados"),
    ("by", "Belarus"),
    ("be", "Belgium"),
    ("bz", "Belize"),
    ("bj", "Benin"),
    ("bt", "Bhutan"),
    ("bo", "Bolivia"),
    ("ba", "Bosnia and Herzegovina"),
    ("bw", "Botswana"),
    ("br", "Brazil"),
    ("bn", "Brunei"),
    ("bg", "Bulgaria"),
    ("bf", "Burkina Faso"),
    ("bi", "Burundi"),
    ("cv", "Cabo Verde"),
    ("kh", "Cambodia"),
    ("cm", "Cameroon"),
    ("ca", "Canada"),
    ("cf", "Central African Republic"),
    ("td", "Chad"),
    ("cl", "Chile"),
    ("cn", "China"),
    ("co", "Colombia"),
    ("km", "Comoros"),
    ("cg", "Congo"),
    ("cr", "Costa Rica"),
    ("ci", "Côte d'Ivoire"),
    ("hr", "Croatia"),
    ("cu", "Cuba"),
    ("cy", "Cyprus"),
    ("cz", "Czechia"),
    ("cd", "Democratic Republic of the Congo"),
    ("dk", "Denmark"),
    ("dj", "Djibouti"),
    ("dm", "Dominica"),
    ("do", "Dominican Republic"),
    ("ec", "Ecuador"),
    ("eg", "Egypt"),
    ("sv", "El Salvador"),
    ("gq", "Equatorial Guinea"),
    ("er", "Eritrea"),
    ("ee", "Estonia"),
    ("sz", "Eswatini"),
    ("et", "Ethiopia"),
    ("fj", "Fiji"),
    ("fi", "Finland"),
    ("fr", "France"),
    ("ga", "Gabon"),
    ("gm", "Gambia"),
    ("ge", "Georgia"),
    ("de", "Germany"),
    ("gh", "Ghana"),
    ("gr", "Greece"),
    ("gd", "Grenada"),
    ("gt", "Guatemala"),
    ("gn", "Guinea"),
    ("gw", "Guinea-Bissau"),
    ("gy", "Guyana"),
    ("ht", "Haiti"),
    ("va", "Holy See"),
    ("hn", "Honduras"),
    ("hk", "Hong Kong"),
    ("hu", "Hungary"),
    ("is", "Iceland"),
    ("in", "India"),
    ("id", "Indonesia"),
    ("ir", "Iran"),
    ("iq", "Iraq"),
    ("ie", "Ireland"),
    ("il", "Israel"),
    ("it", "Italy"),
    ("jm", "Jamaica"),
    ("jp", "Japan"),
    ("jo", "Jordan"),
    ("kz", "Kazakhstan"),
    ("ke", "Kenya"),
    ("ki", "Kiribati"),
    ("xk", "Kosovo"),
    ("kw", "Kuwait"),
    ("kg", "Kyrgyzstan"),
    ("la", "Laos"),
    ("lv", "Latvia"),
    ("lb", "Lebanon"),
    ("ls", "Lesotho"),
    ("lr", "Liberia"),
    ("ly", "Libya"),
    ("li", "Liechtenstein"),
    ("lt", "Lithuania"),
    ("lu", "Luxembourg"),
    ("mo", "Macao"),
    ("mg", "Madagascar"),
    ("mw", "Malawi"),
    ("my", "Malaysia"),
    ("mv", "Maldives"),
    ("ml", "Mali"),
    ("mt", "Malta"),
    ("mh", "Marshall Islands"),
    ("mr", "Mauritania"),
    ("mu", "Mauritius"),
    ("mx", "Mexico"),
    ("fm", "Micronesia"),
    ("md", "Moldova"),
    ("mc", "Monaco"),
    ("mn", "Mongolia"),
    ("me", "Montenegro"),
    ("ma", "Morocco"),
    ("mz", "Mozambique"),
    ("mm", "Myanmar"),
    ("na", "Namibia"),
    ("nr", "Nauru"),
    ("np", "Nepal"),
    ("nl", "Netherlands"),
    ("nz", "New Zealand"),
    ("ni", "Nicaragua"),
    ("ne", "Niger"),
    ("ng", "Nigeria"),
    ("kp", "North Korea"),
    ("mk", "North Macedonia"),
    ("no", "Norway"),
    ("om", "Oman"),
    ("pk", "Pakistan"),
    ("pw", "Palau"),
    ("ps", "Palestine"),
    ("pa", "Panama"),
    ("pg", "Papua New Guinea"),
    ("py", "Paraguay"),
    ("pe", "Peru"),
    ("ph", "Philippines"),
    ("pl", "Poland"),
    ("pt", "Portugal"),
    ("qa", "Qatar"),
    ("ro", "Romania"),
    ("ru", "Russia"),
    ("rw", "Rwanda"),
    ("kn", "Saint Kitts and Nevis"),
    ("lc", "Saint Lucia"),
    ("vc", "Saint Vincent and the Grenadines"),
    ("ws", "Samoa"),
    ("sm", "San Marino"),
    ("st", "São Tomé and Príncipe"),
    ("sa", "Saudi Arabia"),
    ("sn", "Senegal"),
    ("rs", "Serbia"),
    ("sc", "Seychelles"),
    ("sl", "Sierra Leone"),
    ("sg", "Singapore"),
    ("sk", "Slovakia"),
    ("si", "Slovenia"),
    ("sb", "Solomon Islands"),
    ("so", "Somalia"),
    ("za", "South Africa"),
    ("kr", "South Korea"),
    ("ss", "South Sudan"),
    ("es", "Spain"),
    ("lk", "Sri Lanka"),
    ("sd", "Sudan"),
    ("sr", "Suriname"),
    ("se", "Sweden"),
    ("ch", "Switzerland"),
    ("sy", "Syria"),
    ("tw", "Taiwan"),
    ("tj", "Tajikistan"),
    ("tz", "Tanzania"),
    ("th", "Thailand"),
    ("tl", "Timor-Leste"),
    ("tg", "Togo"),
    ("to", "Tonga"),
    ("tt", "Trinidad and Tobago"),
    ("tn", "Tunisia"),
    ("tr", "Türkiye"),
    ("tm", "Turkmenistan"),
    ("tv", "Tuvalu"),
    ("ug", "Uganda"),
    ("ua", "Ukraine"),
    ("ae", "United Arab Emirates"),
    ("gb", "United Kingdom"),
    ("us", "United States"),
    ("uy", "Uruguay"),
    ("uz", "Uzbekistan"),
    ("vu", "Vanuatu"),
    ("ve", "Venezuela"),
    ("vn", "Vietnam"),
    ("ye", "Yemen"),
    ("zm", "Zambia"),
    ("zw", "Zimbabwe"),
)

#: Kod → nazwa, dla odczytu po kodzie (``country_name``).
COUNTRY_NAMES: dict[str, str] = dict(COUNTRIES)


def country_name(code: str) -> str:
    """Angielska nazwa kraju dla kodu alfa-2 (wielkość liter bez znaczenia); pusty napis, gdy brak."""
    return COUNTRY_NAMES.get((code or "").strip().lower(), "")
