# Generated by Django 5.1.15 on 2026-09-05 11:25

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adres e-mail')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='imię')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nazwisko')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywne')),
                ('is_staff', models.BooleanField(default=False, verbose_name='dostęp do panelu admina')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data rejestracji')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'użytkownik',
                'verbose_name_plural': 'użytkownicy',
                'ordering': ('email',),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='okręg')),
                ('status', models.CharField(choices=[('PENDING', 'oczekuje'), ('ACTIVE', 'aktywny'), ('SUSPENDED', 'zawieszony')], default='PENDING', max_length=16, verbose_name='status')),
                ('is_appeals_committee', models.BooleanField(default=False, verbose_name='komisja odwoławcza')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='zatwierdzony')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'członek komitetu',
                'verbose_name_plural': 'członkowie komitetu',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='sha256 kodu')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('expires_at', models.DateTimeField(verbose_name='wygasa')),
                ('max_uses', models.PositiveSmallIntegerField(default=1, verbose_name='limit użyć')),
                ('used_count', models.PositiveSmallIntegerField(default=0, verbose_name='liczba użyć')),
                ('grants_status', models.CharField(choices=[('ACTIVE', 'od razu aktywny'), ('PENDING', 'wymaga zatwierdzenia')], default='ACTIVE', max_length=16, verbose_name='nadawany status')),
                ('is_appeals', models.BooleanField(default=False, verbose_name='uprawnia do komisji odwoławczej')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'kod zaproszenia',
                'verbose_name_plural': 'kody zaproszeń',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_code', models.CharField(default=apps.accounts.models.generate_public_code, max_length=16, unique=True, verbose_name='kod publiczny')),
                ('school', models.CharField(max_length=200, verbose_name='szkoła')),
                ('district', models.CharField(max_length=100, verbose_name='okręg')),
                ('birth_year', models.PositiveSmallIntegerField(verbose_name='rok urodzenia')),
                ('gdpr_consent_at', models.DateTimeField(verbose_name='zgoda RODO z dnia')),
                ('guardian_consent', models.BooleanField(default=False, verbose_name='zgoda opiekuna')),
                ('publish_full_name', models.BooleanField(default=False, verbose_name='zgoda na publikację pełnych danych')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uczestnik',
                'verbose_name_plural': 'uczestnicy',
                'ordering': ('public_code',),
            },
        ),
    ]
