# Generated by Django 5.1.15 on 2026-09-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_ci_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='district_verified',
            field=models.BooleanField(default=False, verbose_name='okręg zweryfikowany'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='okręg'),
        ),
    ]
