# Generated by Django 5.1.15 on 2026-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_committeemember_district_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemember",
            name="district_verified",
            field=models.BooleanField(default=False, verbose_name="województwo zweryfikowane"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="district",
            field=models.CharField(max_length=100, verbose_name="województwo"),
        ),
    ]
