# Generated by Django 5.1.15 on 2026-09-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_district_wording_wojewodztwo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemember",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dolnoslaskie", "dolnośląskie"),
                    ("kujawsko-pomorskie", "kujawsko-pomorskie"),
                    ("lubelskie", "lubelskie"),
                    ("lubuskie", "lubuskie"),
                    ("lodzkie", "łódzkie"),
                    ("malopolskie", "małopolskie"),
                    ("mazowieckie", "mazowieckie"),
                    ("opolskie", "opolskie"),
                    ("podkarpackie", "podkarpackie"),
                    ("podlaskie", "podlaskie"),
                    ("pomorskie", "pomorskie"),
                    ("slaskie", "śląskie"),
                    ("swietokrzyskie", "świętokrzyskie"),
                    ("warminsko-mazurskie", "warmińsko-mazurskie"),
                    ("wielkopolskie", "wielkopolskie"),
                    ("zachodniopomorskie", "zachodniopomorskie"),
                ],
                max_length=100,
                null=True,
                verbose_name="województwo",
            ),
        ),
        migrations.AlterField(
            model_name="invitationcode",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dolnoslaskie", "dolnośląskie"),
                    ("kujawsko-pomorskie", "kujawsko-pomorskie"),
                    ("lubelskie", "lubelskie"),
                    ("lubuskie", "lubuskie"),
                    ("lodzkie", "łódzkie"),
                    ("malopolskie", "małopolskie"),
                    ("mazowieckie", "mazowieckie"),
                    ("opolskie", "opolskie"),
                    ("podkarpackie", "podkarpackie"),
                    ("podlaskie", "podlaskie"),
                    ("pomorskie", "pomorskie"),
                    ("slaskie", "śląskie"),
                    ("swietokrzyskie", "świętokrzyskie"),
                    ("warminsko-mazurskie", "warmińsko-mazurskie"),
                    ("wielkopolskie", "wielkopolskie"),
                    ("zachodniopomorskie", "zachodniopomorskie"),
                ],
                max_length=100,
                null=True,
                verbose_name="województwo",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="district",
            field=models.CharField(
                choices=[
                    ("dolnoslaskie", "dolnośląskie"),
                    ("kujawsko-pomorskie", "kujawsko-pomorskie"),
                    ("lubelskie", "lubelskie"),
                    ("lubuskie", "lubuskie"),
                    ("lodzkie", "łódzkie"),
                    ("malopolskie", "małopolskie"),
                    ("mazowieckie", "mazowieckie"),
                    ("opolskie", "opolskie"),
                    ("podkarpackie", "podkarpackie"),
                    ("podlaskie", "podlaskie"),
                    ("pomorskie", "pomorskie"),
                    ("slaskie", "śląskie"),
                    ("swietokrzyskie", "świętokrzyskie"),
                    ("warminsko-mazurskie", "warmińsko-mazurskie"),
                    ("wielkopolskie", "wielkopolskie"),
                    ("zachodniopomorskie", "zachodniopomorskie"),
                ],
                max_length=100,
                verbose_name="województwo",
            ),
        ),
    ]
