# Generated by Django 5.1.15 on 2026-09-10 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_district_normalise_voivodeship'),
        ('schools', '0001_schools_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='klasa'),
        ),
        migrations.AddField(
            model_name='participant',
            name='school_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='schools.school', verbose_name='szkoła z rejestru'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='school',
            field=models.CharField(max_length=255, verbose_name='szkoła'),
        ),
    ]
