# Generated by Django 5.1.15 on 2026-09-10 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_schools_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='regulamin zaakceptowany'),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TERMS', 'akceptacja regulaminu'), ('PRIVACY', 'przetwarzanie danych osobowych'), ('GUARDIAN', 'zgoda rodzica lub opiekuna prawnego'), ('PUBLISH_NAME', 'publikacja imienia i nazwiska')], max_length=20, verbose_name='rodzaj')),
                ('document_version', models.CharField(blank=True, max_length=100, verbose_name='wersja dokumentu')),
                ('given_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='wyrażona')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='wycofana')),
                ('source', models.CharField(choices=[('web', 'formularz WWW'), ('api', 'API'), ('social', 'logowanie przez dostawcę zewnętrznego'), ('panel', 'panel uczestnika')], max_length=16, verbose_name='droga')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='accounts.participant', verbose_name='uczestnik')),
            ],
            options={
                'verbose_name': 'zgoda uczestnika',
                'verbose_name_plural': 'zgody uczestników',
                'ordering': ('-given_at', '-id'),
                'indexes': [models.Index(fields=['participant', 'kind'], name='accounts_consent_pk_idx')],
            },
        ),
    ]
