# Generated by Django 5.1.15 on 2026-09-16 18:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_message_broadcast'),
        ('competitions', '0014_problem_model_solution_stage_review_days'),
        ('schools', '0001_schools_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='supervisor_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='adres opiekuna szkolnego'),
        ),
        migrations.CreateModel(
            name='SchoolSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=255, verbose_name='szkoła')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('verified', models.BooleanField(default=False, verbose_name='dane szkoły zweryfikowane')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('school_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='schools.school', verbose_name='szkoła z rejestru')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'opiekun szkolny',
                'verbose_name_plural': 'opiekunowie szkolni',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SchoolParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='potwierdzone')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_participations', to='competitions.edition')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='accounts.schoolsupervisor')),
            ],
            options={
                'verbose_name': 'udział szkoły w edycji',
                'verbose_name_plural': 'udziały szkół w edycjach',
                'ordering': ('-confirmed_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('supervisor', 'edition'), name='accounts_school_participation_unique')],
            },
        ),
    ]
