# Generated by Django 5.1.15 on 2026-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_supervisor_rbac_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='given_by_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='potwierdzone z adresu'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='adres IP'),
        ),
        migrations.AddField(
            model_name='participant',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='adres e-mail opiekuna'),
        ),
    ]
