# Generated by Django 5.1.15 on 2026-09-16 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_guardian_consent_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=8, verbose_name='język interfejsu')),
                ('high_contrast', models.BooleanField(default=False, verbose_name='tryb wysokiego kontrastu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmienione')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ustawienia interfejsu',
                'verbose_name_plural': 'ustawienia interfejsu',
            },
        ),
    ]
