# Generated by Django 5.1.15 on 2026-09-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_interface_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='zaproszenie wysłane'),
        ),
        migrations.AddField(
            model_name='participant',
            name='invited_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='zaproszony z importu'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gdpr_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='zgoda RODO z dnia'),
        ),
    ]
