# Generated by Django 6.1.1 on 2026-09-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, max_length=255, verbose_name='stary adres')),
                ('new_path', models.CharField(max_length=500, verbose_name='nowy adres')),
                ('is_permanent', models.BooleanField(default=True, verbose_name='stałe (301)')),
                ('source', models.CharField(choices=[('import', 'import z Wagtaila'), ('auto', 'zmiana adresu strony'), ('manual', 'redakcja')], default='manual', max_length=8, verbose_name='źródło')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dj_redirects', to='sites.site')),
            ],
            options={
                'verbose_name': 'przekierowanie',
                'verbose_name_plural': 'przekierowania',
                'ordering': ('site', 'old_path'),
                'constraints': [models.UniqueConstraint(fields=('site', 'old_path'), name='dj_seo_unique_site_old_path')],
            },
        ),
    ]
