# Generated by Django 6.1.1 on 2026-10-04 17:44

import apps.alumni.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0035_committee_video_room_issuer'),
        ('chat', '0002_reply_templates_status_age_limit'),
        ('tenancy', '0012_competition_site_logo_social_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('GRANTED', 'zgoda udzielona'), ('WITHDRAWN', 'zgoda wycofana')], max_length=10, verbose_name='zdarzenie')),
                ('version', models.CharField(max_length=32, verbose_name='wersja treści')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='chwila')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_consent_events', to='accounts.participant', verbose_name='uczestnik')),
            ],
            options={
                'verbose_name': 'zgoda absolwenta (zdarzenie)',
                'verbose_name_plural': 'zgody absolwentów (zdarzenia)',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AlumniInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('WORKSHOP', 'warsztaty'), ('WEBINAR', 'webinar'), ('JURY', 'jury'), ('OTHER', 'inne')], max_length=10, verbose_name='rodzaj')),
                ('title', models.CharField(max_length=150, verbose_name='tytuł')),
                ('body', models.TextField(max_length=4000, verbose_name='treść')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='adres wydarzenia')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filtry')),
                ('recipients', models.PositiveIntegerField(default=0, verbose_name='liczba odbiorców')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='wysłane')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.competition', verbose_name='konkurs')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='wysłał')),
            ],
            options={
                'verbose_name': 'zaproszenie absolwentów',
                'verbose_name_plural': 'zaproszenia absolwentów',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AlumniSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility', models.CharField(choices=[('ANY', 'uczestnik'), ('QUALIFIED', 'awans do kolejnego etapu'), ('FINALIST', 'finalista'), ('LAUREATE', 'laureat')], default='FINALIST', max_length=12, verbose_name='kto może dołączyć')),
                ('mentoring_enabled', models.BooleanField(default=False, verbose_name='mentoring włączony')),
                ('public_wall', models.BooleanField(default=False, verbose_name='publiczna ściana absolwentów')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmienione')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_settings', to='tenancy.competition', verbose_name='konkurs')),
            ],
            options={
                'verbose_name': 'ustawienia sieci absolwentów',
                'verbose_name_plural': 'ustawienia sieci absolwentów',
            },
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'prośba czeka na mentora'), ('ACCEPTED', 'trwa'), ('DECLINED', 'odrzucona przez mentora'), ('CANCELLED', 'wycofana przez uczestnika'), ('ENDED', 'zakończona')], default='REQUESTED', max_length=10, verbose_name='stan')),
                ('topic', models.CharField(blank=True, choices=[('quantum_computing', 'obliczenia kwantowe'), ('quantum_physics', 'fizyka kwantowa'), ('physics', 'fizyka'), ('computer_science', 'informatyka'), ('mathematics', 'matematyka'), ('engineering', 'inżynieria'), ('chemistry', 'chemia'), ('research', 'badania naukowe'), ('industry', 'praca w przemyśle'), ('education', 'edukacja i popularyzacja')], max_length=32, verbose_name='temat')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='notatka prośby')),
                ('conversation_preexisting', models.BooleanField(default=False, verbose_name='rozmowa sprzed mentoringu')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='prośba')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='odpowiedź mentora')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='zakończona')),
                ('end_reason', models.CharField(blank=True, choices=[('MENTOR', 'zakończył mentor'), ('MENTEE', 'zakończył uczestnik'), ('COORDINATOR', 'zakończył organizator'), ('WITHDRAWN', 'mentor wycofał zgodę'), ('ACCOUNT_REMOVED', 'konto usunięte')], max_length=16, verbose_name='powód zakończenia')),
                ('coordinator_note', models.CharField(blank=True, max_length=500, verbose_name='notatka organizatora')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.competition', verbose_name='konkurs')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorships', to='chat.conversation', verbose_name='rozmowa')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='zakończył')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentee', to='accounts.participant', verbose_name='uczestnik')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships_as_mentor', to='accounts.participant', verbose_name='mentor')),
            ],
            options={
                'verbose_name': 'mentoring',
                'verbose_name_plural': 'mentoring',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MentorshipFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='powód')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zgłoszone')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='rozpatrzone')),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='alumni.mentorship', verbose_name='mentoring')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='zgłaszający')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='rozpatrzył')),
            ],
            options={
                'verbose_name': 'zgłoszenie mentoringu',
                'verbose_name_plural': 'zgłoszenia mentoringu',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.alumni.models.new_token, max_length=32, unique=True, verbose_name='identyfikator')),
                ('consent_version', models.CharField(max_length=32, verbose_name='wersja zgody')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dołączył')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmieniony')),
                ('show_full_name', models.BooleanField(default=False, verbose_name='pełne imię i nazwisko')),
                ('university', models.CharField(blank=True, max_length=120, verbose_name='uczelnia')),
                ('field_of_study', models.CharField(blank=True, max_length=120, verbose_name='kierunek')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='miasto')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='kraj')),
                ('bio', models.TextField(blank=True, max_length=600, verbose_name='o mnie')),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='zainteresowania')),
                ('linkedin_url', models.URLField(blank=True, max_length=300, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, max_length=300, verbose_name='GitHub')),
                ('mentor_available', models.BooleanField(default=False, verbose_name='dostępny jako mentor')),
                ('mentor_topics', models.JSONField(blank=True, default=list, verbose_name='tematy mentoringu')),
                ('mentor_capacity', models.PositiveSmallIntegerField(default=2, verbose_name='ilu mentee naraz')),
                ('listed', models.BooleanField(default=True, verbose_name='widoczny w katalogu')),
                ('public', models.BooleanField(default=False, verbose_name='na publicznej ścianie')),
                ('invitations', models.BooleanField(default=True, verbose_name='zaproszenia od organizatora')),
                ('hidden_at', models.DateTimeField(blank=True, null=True, verbose_name='ukryty przez koordynatora')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ukrył')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to='accounts.participant', verbose_name='uczestnik')),
            ],
            options={
                'verbose_name': 'profil absolwenta',
                'verbose_name_plural': 'profile absolwentów',
                'ordering': ('-joined_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('mentor_capacity__gte', 1), ('mentor_capacity__lte', 10)), name='alumni_profile_capacity_range')],
            },
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['competition', 'status', '-created_at'], name='alumni_mentorship_list_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentorship',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REQUESTED', 'ACCEPTED'])), fields=('mentor', 'mentee'), name='alumni_one_open_mentorship_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='mentorship',
            constraint=models.CheckConstraint(condition=models.Q(('mentor', models.F('mentee')), _negated=True), name='alumni_mentor_not_mentee'),
        ),
    ]
