# Generated by Django 6.1.1 on 2026-10-04 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def confirm_adults(apps, schema_editor):
    """Profile sprzed tej migracji powstały wyłącznie dla osób pełnoletnich (reguła dołączenia)."""
    AlumniProfile = apps.get_model("alumni", "AlumniProfile")
    AlumniProfile.objects.filter(adult_confirmed_at__isnull=True).update(adult_confirmed_at=models.F("joined_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniconsentevent',
            name='language',
            field=models.CharField(blank=True, max_length=16, verbose_name='język treści'),
        ),
        migrations.AddField(
            model_name='alumniconsentevent',
            name='text_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='skrót treści'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='adult_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pełnoletność potwierdzona'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='treść zaakceptowana'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='zaakceptował treść'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='reviewed_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='skrót zaakceptowanej treści'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data urodzenia mentee przy akceptacji'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee_birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rocznik mentee przy akceptacji'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='note_status',
            field=models.CharField(blank=True, choices=[('', 'bez akceptacji'), ('PENDING', 'czeka na organizatora'), ('APPROVED', 'zaakceptowana'), ('REJECTED', 'odrzucona przez organizatora')], default='', max_length=10, verbose_name='akceptacja notatki'),
        ),
        migrations.AddField(
            model_name='mentorshipflag',
            name='automatic',
            field=models.BooleanField(default=False, verbose_name='automatyczne'),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('MENTOR', 'zakończył mentor'), ('MENTEE', 'zakończył uczestnik'), ('COORDINATOR', 'zakończył organizator'), ('WITHDRAWN', 'mentor wycofał zgodę'), ('ACCOUNT_REMOVED', 'konto usunięte'), ('HIDDEN', 'profil mentora ukryty przez organizatora')], max_length=16, verbose_name='powód zakończenia'),
        ),
        migrations.RunPython(confirm_adults, migrations.RunPython.noop),
    ]
