# Generated by Django 5.1.15 on 2026-09-05 12:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0002_stage_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='wersja')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='oddane')),
                ('is_late', models.BooleanField(default=False, verbose_name='po deadline (w tolerancji)')),
                ('status', models.CharField(choices=[('SUBMITTED', 'oddane'), ('SCANNING', 'skanowanie'), ('REJECTED_INFECTED', 'odrzucone (wirus)'), ('LOCKED', 'zablokowane'), ('IN_REVIEW', 'w ocenie'), ('MODERATION', 'moderacja'), ('GRADED_PROVISIONAL', 'ocena wstępna'), ('APPEALED', 'reklamacja'), ('FINAL', 'ocena ostateczna')], default='SUBMITTED', max_length=24, verbose_name='status')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competitions.stageentry')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competitions.problem')),
            ],
            options={
                'verbose_name': 'rozwiązanie',
                'verbose_name_plural': 'rozwiązania',
                'ordering': ('-submitted_at', '-version', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=512, unique=True, verbose_name='klucz obiektu')),
                ('sha256', models.CharField(max_length=64, verbose_name='sha256')),
                ('original_name', models.CharField(max_length=255, verbose_name='nazwa od użytkownika')),
                ('mime', models.CharField(max_length=100, verbose_name='typ MIME')),
                ('size_bytes', models.BigIntegerField(verbose_name='rozmiar (B)')),
                ('av_status', models.CharField(choices=[('PENDING', 'oczekuje na skan'), ('CLEAN', 'czysty'), ('INFECTED', 'zainfekowany')], default='PENDING', max_length=16, verbose_name='status skanu')),
                ('av_signature', models.CharField(blank=True, max_length=200, verbose_name='sygnatura wirusa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='zeskanowany')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'plik rozwiązania',
                'verbose_name_plural': 'pliki rozwiązań',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('entry', 'problem', 'version'), name='submissions_submission_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='submissions_submission_version_positive'),
        ),
    ]
