# Generated by Django 5.1.15 on 2026-09-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='av_status',
            field=models.CharField(choices=[('PENDING', 'oczekuje na skan'), ('CLEAN', 'czysty'), ('INFECTED', 'zainfekowany'), ('ERROR', 'błąd skanu')], default='PENDING', max_length=16, verbose_name='status skanu'),
        ),
    ]
