# Generated by Django 5.1.15 on 2026-09-16 18:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_school_supervisors_and_quality'),
        ('submissions', '0002_alter_submissionfile_av_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='podobieństwo')),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='policzone')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='zgłoszona do komitetu')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='competitions.problem')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_similarities', to=settings.AUTH_USER_MODEL, verbose_name='zgłosił')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='competitions.stage')),
                ('submission_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_a', to='submissions.submission', verbose_name='praca A')),
                ('submission_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_b', to='submissions.submission', verbose_name='praca B')),
            ],
            options={
                'verbose_name': 'podobieństwo rozwiązań',
                'verbose_name_plural': 'podobieństwa rozwiązań',
                'ordering': ('-score', 'id'),
                'constraints': [models.UniqueConstraint(fields=('problem', 'submission_a', 'submission_b'), name='submissions_similarity_unique_pair'), models.CheckConstraint(condition=models.Q(('submission_a__lt', models.F('submission_b'))), name='submissions_similarity_ordered_pair'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 1)), name='submissions_similarity_score_range')],
            },
        ),
    ]
