# Generated by Django 5.1.15 on 2026-09-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_school_supervisors_and_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='liczba stron'),
        ),
    ]
