# Generated by Django 5.1.15 on 2026-09-17 12:26

import apps.competitions.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0018_alter_stage_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='tytuł')),
                ('instructions', models.TextField(blank=True, verbose_name='instrukcja')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, help_text='Licznik jednego podejścia. Koniec okna testu i tak zamyka podejście wcześniej.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='czas trwania (minuty)')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='otwarcie testu')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='zamknięcie testu')),
                ('attempts_allowed', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='liczba podejść')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='losowa kolejność pytań')),
                ('shuffle_options', models.BooleanField(default=False, verbose_name='losowa kolejność wariantów')),
                ('questions_per_attempt', models.PositiveSmallIntegerField(blank=True, help_text='Puste = wszystkie pytania. Wpisana liczba = tyle pytań losowanych z każdej puli.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='pytań z każdej puli')),
                ('show_results_after', models.CharField(choices=[('NEVER', 'nigdy (wynik tylko w tabeli wyników etapu)'), ('AFTER_CLOSE', 'po zamknięciu testu'), ('IMMEDIATELY', 'od razu po zakończeniu podejścia')], default='AFTER_CLOSE', max_length=16, verbose_name='pokaż wynik')),
                ('negative_floor', models.CharField(choices=[('QUESTION', 'zero za pytanie (ujemne nie schodzą poniżej zera w pytaniu)'), ('QUIZ', 'zero za test (ujemne przenoszą się między pytaniami)')], default='QUESTION', max_length=16, verbose_name='podłoga punktów ujemnych')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniony')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='competitions.stage', verbose_name='etap')),
            ],
            options={
                'verbose_name': 'test online',
                'verbose_name_plural': 'testy online',
                'ordering': ('stage', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='rozpoczęte')),
                ('deadline_at', models.DateTimeField(verbose_name='koniec podejścia')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='zakończone')),
                ('question_order', models.JSONField(blank=True, default=dict, verbose_name='wylosowany zestaw')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='wynik')),
                ('max_points', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='maksimum zestawu')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'w trakcie'), ('SUBMITTED', 'zakończone'), ('EXPIRED', 'czas minął')], default='IN_PROGRESS', max_length=16, verbose_name='status')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='ocenione')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adres IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='przeglądarka')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='competitions.stageentry', verbose_name='wpis do etapu')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz', verbose_name='test')),
            ],
            options={
                'verbose_name': 'podejście do testu',
                'verbose_name_plural': 'podejścia do testu',
                'ordering': ('-started_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.CharField(blank=True, max_length=40, verbose_name='pula')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('kind', models.CharField(choices=[('SINGLE_CHOICE', 'jednokrotny wybór'), ('MULTIPLE_CHOICE', 'wielokrotny wybór'), ('SHORT_TEXT', 'krótka odpowiedź tekstowa'), ('NUMERIC', 'odpowiedź liczbowa')], default='SINGLE_CHOICE', max_length=20, verbose_name='rodzaj')),
                ('text', models.TextField(verbose_name='treść')),
                ('image', models.ImageField(blank=True, null=True, storage=apps.competitions.storage.private_media_storage, upload_to='quiz-questions/', verbose_name='ilustracja')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, verbose_name='punkty')),
                ('negative_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='punkty ujemne za błąd')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='ustawienia sprawdzania')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='test')),
            ],
            options={
                'verbose_name': 'pytanie testu',
                'verbose_name_plural': 'pytania testu',
                'ordering': ('quiz', 'pool', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('text', models.CharField(max_length=500, verbose_name='treść')),
                ('is_correct', models.BooleanField(default=False, verbose_name='poprawny')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.quizquestion', verbose_name='pytanie')),
            ],
            options={
                'verbose_name': 'wariant odpowiedzi',
                'verbose_name_plural': 'warianty odpowiedzi',
                'ordering': ('question', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='odpowiedź')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='poprawna')),
                ('points_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='przyznane punkty')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zapisana')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt', verbose_name='podejście')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizquestion', verbose_name='pytanie')),
            ],
            options={
                'verbose_name': 'odpowiedź w teście',
                'verbose_name_plural': 'odpowiedzi w teście',
                'ordering': ('attempt', 'question'),
            },
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at__isnull', True), ('closes_at__isnull', True), ('opens_at__lt', models.F('closes_at')), _connector='OR'), name='quiz_quiz_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1)), name='quiz_quiz_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('attempts_allowed__gte', 1)), name='quiz_quiz_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('questions_per_attempt__isnull', True), ('questions_per_attempt__gte', 1), _connector='OR'), name='quiz_quiz_draw_positive'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('quiz', 'entry'), name='quiz_attempt_single_active'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__gt', models.F('started_at'))), name='quiz_attempt_deadline_after_start'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', 0), ('points__lte', Decimal('100'))), name='quiz_question_points_in_range'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.CheckConstraint(condition=models.Q(('negative_points__gte', 0), ('negative_points__lte', models.F('points'))), name='quiz_question_negative_within_points'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='quiz_answer_unique_per_question'),
        ),
    ]
