# Generated by Django 5.1.15 on 2026-09-05 11:49

import apps.competitions.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_email_ci_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=64, unique=True, verbose_name='oznaczenie edycji')),
                ('is_current', models.BooleanField(default=False, verbose_name='edycja bieżąca')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzona')),
            ],
            options={
                'verbose_name': 'edycja',
                'verbose_name_plural': 'edycje',
                'ordering': ('-created_at', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='competitions_edition_single_current')],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ELIM', 'Eliminacje'), ('DISTRICT', 'Okręgowy'), ('FINAL', 'Finał')], max_length=16, verbose_name='rodzaj')),
                ('opens_at', models.DateTimeField(verbose_name='otwarcie')),
                ('deadline_at', models.DateTimeField(verbose_name='deadline oddania')),
                ('grace_seconds', models.PositiveIntegerField(default=0, verbose_name='tolerancja po deadline (s)')),
                ('review_deadline_at', models.DateTimeField(verbose_name='deadline recenzji')),
                ('appeal_window_opens_at', models.DateTimeField(verbose_name='otwarcie okna reklamacji')),
                ('appeal_window_closes_at', models.DateTimeField(verbose_name='zamknięcie okna reklamacji')),
                ('results_published_at', models.DateTimeField(blank=True, null=True, verbose_name='wyniki opublikowane')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='competitions.edition')),
            ],
            options={
                'verbose_name': 'etap',
                'verbose_name_plural': 'etapy',
                'ordering': ('edition', 'opens_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ScoringScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=apps.competitions.models.default_scoring_values, verbose_name='wartości skali')),
                ('max_value', models.PositiveSmallIntegerField(default=6, verbose_name='maksimum')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_scale', to='competitions.stage')),
            ],
            options={
                'verbose_name': 'skala punktacji',
                'verbose_name_plural': 'skale punktacji',
            },
        ),
        migrations.CreateModel(
            name='QualificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('MIN_POINTS', 'min. punktów'), ('TOP_N', 'najlepszych N'), ('TOP_N_PER_DISTRICT', 'N na okręg'), ('HYBRID', 'min. punktów ORAZ top N')], default='MIN_POINTS', max_length=32, verbose_name='tryb')),
                ('min_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='minimum punktów')),
                ('top_n', models.PositiveIntegerField(blank=True, null=True, verbose_name='liczba kwalifikowanych')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_rule', to='competitions.stage')),
            ],
            options={
                'verbose_name': 'próg kwalifikacji',
                'verbose_name_plural': 'progi kwalifikacji',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='numer')),
                ('title', models.CharField(max_length=300, verbose_name='tytuł')),
                ('statement_pdf', models.FileField(blank=True, upload_to='problems/statements/', verbose_name='treść (PDF)')),
                ('allowed_formats', models.JSONField(default=apps.competitions.models.default_allowed_formats, verbose_name='dozwolone formaty')),
                ('max_file_mb', models.PositiveSmallIntegerField(default=20, verbose_name='limit rozmiaru pliku (MB)')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='competitions.stage')),
            ],
            options={
                'verbose_name': 'zadanie',
                'verbose_name_plural': 'zadania',
                'ordering': ('stage', 'number'),
            },
        ),
        migrations.CreateModel(
            name='StageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'zarejestrowany'), ('QUALIFIED', 'zakwalifikowany'), ('NOT_QUALIFIED', 'niezakwalifikowany'), ('DISQUALIFIED', 'zdyskwalifikowany')], default='REGISTERED', max_length=16, verbose_name='status')),
                ('total_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='suma punktów')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_entries', to='accounts.participant')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.stage')),
            ],
            options={
                'verbose_name': 'wpis do etapu',
                'verbose_name_plural': 'wpisy do etapów',
                'ordering': ('stage', 'participant'),
            },
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('edition', 'kind'), name='competitions_stage_unique_kind'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at__lt', models.F('deadline_at'))), name='competitions_stage_opens_before_deadline'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__lte', models.F('review_deadline_at'))), name='competitions_stage_deadline_before_review'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('review_deadline_at__lte', models.F('appeal_window_opens_at'))), name='competitions_stage_review_before_appeal'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('appeal_window_opens_at__lt', models.F('appeal_window_closes_at'))), name='competitions_stage_appeal_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.UniqueConstraint(fields=('stage', 'number'), name='competitions_problem_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='competitions_problem_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.CheckConstraint(condition=models.Q(('max_file_mb__gte', 1)), name='competitions_problem_max_file_mb_positive'),
        ),
        migrations.AddConstraint(
            model_name='stageentry',
            constraint=models.UniqueConstraint(fields=('participant', 'stage'), name='competitions_stageentry_unique_participant'),
        ),
    ]
