# Generated by Django 5.1.15 on 2026-09-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='etap zamknięty'),
        ),
    ]
