# Generated by Django 5.1.15 on 2026-09-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_stage_closed_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.CheckConstraint(condition=models.Q(('max_file_mb__lte', 100)), name='competitions_problem_max_file_mb_under_limit'),
        ),
    ]
