# Generated by Django 5.1.15 on 2026-09-05 15:02

import apps.competitions.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_problem_competitions_problem_max_file_mb_under_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement_pdf',
            field=models.FileField(blank=True, storage=apps.competitions.storage.private_media_storage, upload_to='problems/statements/', verbose_name='treść (PDF)'),
        ),
    ]
