# Generated by Django 5.1.15 on 2026-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_problem_statement_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='miejsce'),
        ),
    ]
