# Generated by Django 5.1.15 on 2026-09-09 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_stage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='format',
            field=models.CharField(choices=[('SUBMISSIONS', 'rozwiązania pisemne'), ('INTERVIEW', 'rozmowa kwalifikacyjna online')], default='SUBMISSIONS', max_length=16, verbose_name='forma'),
        ),
        migrations.AddField(
            model_name='stage',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='nazwa'),
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='początek')),
                ('ends_at', models.DateTimeField(verbose_name='koniec')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='liczba miejsc')),
                ('meeting_url', models.URLField(blank=True, max_length=500, verbose_name='link do rozmowy')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='oznaczenie')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to='competitions.stage')),
            ],
            options={
                'verbose_name': 'termin rozmowy',
                'verbose_name_plural': 'terminy rozmów',
                'ordering': ('stage', 'starts_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InterviewBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_booking', to='competitions.stageentry')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='competitions.interviewslot')),
            ],
            options={
                'verbose_name': 'zapis na rozmowę',
                'verbose_name_plural': 'zapisy na rozmowy',
                'ordering': ('slot', 'created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='interviewslot',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='competitions_interviewslot_starts_before_ends'),
        ),
        migrations.AddConstraint(
            model_name='interviewslot',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='competitions_interviewslot_capacity_positive'),
        ),
    ]
