# Generated by Django 5.1.15 on 2026-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0007_district_stage_is_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualificationrule",
            name="mode",
            field=models.CharField(
                choices=[
                    ("MIN_POINTS", "min. punktów"),
                    ("TOP_N", "najlepszych N"),
                    ("TOP_N_PER_DISTRICT", "N na województwo"),
                    ("HYBRID", "min. punktów ORAZ top N"),
                ],
                default="MIN_POINTS",
                max_length=32,
                verbose_name="tryb",
            ),
        ),
        migrations.AlterField(
            model_name="stage",
            name="kind",
            field=models.CharField(
                choices=[("ELIM", "Eliminacje"), ("DISTRICT", "Wojewódzki"), ("FINAL", "Finał")],
                max_length=16,
                verbose_name="rodzaj",
            ),
        ),
    ]
