# Generated by Django 5.1.15 on 2026-09-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_district_wording_wojewodztwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='zamknięcie rejestracji'),
        ),
        migrations.AddField(
            model_name='edition',
            name='registration_enabled',
            field=models.BooleanField(default=True, verbose_name='rejestracja włączona'),
        ),
        migrations.AddField(
            model_name='edition',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='otwarcie rejestracji'),
        ),
        migrations.AddConstraint(
            model_name='edition',
            constraint=models.CheckConstraint(condition=models.Q(('registration_opens_at__isnull', True), ('registration_closes_at__isnull', True), ('registration_opens_at__lt', models.F('registration_closes_at')), _connector='OR'), name='competitions_edition_registration_window_ordered'),
        ),
    ]
