# Generated by Django 5.1.15 on 2026-09-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_edition_registration_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='event_ends_on',
            field=models.DateField(blank=True, null=True, verbose_name='koniec wydarzenia'),
        ),
        migrations.AddField(
            model_name='stage',
            name='event_starts_on',
            field=models.DateField(blank=True, null=True, verbose_name='początek wydarzenia'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('event_starts_on__lte', models.F('event_ends_on'))), name='competitions_stage_event_dates_ordered'),
        ),
    ]
