# Generated by Django 5.1.15 on 2026-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_stage_event_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='kind',
            field=models.CharField(choices=[('ELIM', 'Eliminacje'), ('DISTRICT', 'Wojewódzki'), ('FINAL', 'Finał'), ('TRAINING', 'Trening')], max_length=16, verbose_name='rodzaj'),
        ),
    ]
