# Generated by Django 5.1.15 on 2026-09-15 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_stage_training_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='nazwa')),
                ('starts_on', models.DateField(verbose_name='początek')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='koniec')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='dopisek')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='odnośnik')),
                ('show_on_timeline', models.BooleanField(default=True, verbose_name='na linii czasu')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzone')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='dodane przez')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='competitions.edition')),
            ],
            options={
                'verbose_name': 'wydarzenie edycji',
                'verbose_name_plural': 'wydarzenia edycji',
                'ordering': ('starts_on', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='competitions_editionevent_ends_after_starts')],
            },
        ),
    ]
