# Generated by Django 5.1.15 on 2026-09-16 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_school_supervisors_and_quality'),
        ('competitions', '0014_problem_model_solution_stage_review_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stageentry',
            name='manual_qualification',
            field=models.CharField(blank=True, choices=[('', 'bez decyzji komitetu'), ('QUALIFIED', 'zakwalifikowany decyzją komitetu'), ('NOT_QUALIFIED', 'niezakwalifikowany decyzją komitetu')], default='', max_length=16, verbose_name='kwalifikacja ręczna'),
        ),
        migrations.AddField(
            model_name='stageentry',
            name='manual_qualification_reason',
            field=models.TextField(blank=True, verbose_name='uzasadnienie decyzji'),
        ),
        migrations.AddField(
            model_name='stageentry',
            name='manual_qualified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='decyzja z dnia'),
        ),
        migrations.AddField(
            model_name='stageentry',
            name='manual_qualified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_qualifications', to=settings.AUTH_USER_MODEL, verbose_name='decyzję podjął'),
        ),
        migrations.AddConstraint(
            model_name='stageentry',
            constraint=models.CheckConstraint(condition=models.Q(('manual_qualification', ''), models.Q(('manual_qualification_reason', ''), _negated=True), _connector='OR'), name='competitions_stageentry_manual_reason_required'),
        ),
    ]
