# Generated by Django 5.1.15 on 2026-09-16 18:29

import apps.competitions.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_school_supervisors_and_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewbooking',
            name='meeting_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='link do rozmowy'),
        ),
        migrations.AddField(
            model_name='interviewbooking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='przypomnienie wysłane'),
        ),
        migrations.AddField(
            model_name='problem',
            name='statement_pdf_en',
            field=models.FileField(blank=True, storage=apps.competitions.storage.private_media_storage, upload_to='problems/statements-en/', verbose_name='treść (PDF, EN)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='tytuł (EN)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='video_base_url',
            field=models.URLField(blank=True, default='https://meet.jit.si/', verbose_name='adres serwera wideo'),
        ),
        migrations.AddField(
            model_name='stage',
            name='video_provider',
            field=models.CharField(choices=[('none', 'bez wideo (link wpisuje koordynator)'), ('jitsi', 'Jitsi Meet'), ('custom', 'własna instancja')], default='none', max_length=16, verbose_name='dostawca wideo'),
        ),
    ]
