# Generated by Django 5.1.15 on 2026-09-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_edition_data_retention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='format',
            field=models.CharField(choices=[('SUBMISSIONS', 'rozwiązania pisemne'), ('INTERVIEW', 'rozmowa kwalifikacyjna online'), ('QUIZ', 'test online sprawdzany automatycznie')], default='SUBMISSIONS', max_length=16, verbose_name='forma'),
        ),
    ]
