# Generated by Django 6.1.1 on 2026-10-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_video_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='video_provider',
            field=models.CharField(choices=[('none', 'bez wideo (link wpisuje koordynator)'), ('jitsi', 'Jitsi Meet'), ('custom', 'własna instancja'), ('livekit', 'LiveKit (pokój na platformie)')], default='none', max_length=16, verbose_name='dostawca wideo'),
        ),
    ]
