# Generated by Django 6.1.1 on 2026-09-26 16:26

import django.core.validators
import django.db.models.deletion
import djangocms_text.fields
import filer.fields.file
import filer.fields.image
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
        ('filer', '0018_alter_file_options'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='nagłówek sekcji')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BecomePartner',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Zostań partnerem', max_length=200, verbose_name='nagłówek sekcji')),
                ('body', djangocms_text.fields.HTMLField(verbose_name='zaproszenie do współpracy')),
                ('contact_email', models.EmailField(blank=True, help_text='Adres przycisku „Napisz do nas”. Puste = bez przycisku.', max_length=254, verbose_name='e-mail w sprawie współpracy')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DefinitionItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('term', models.CharField(max_length=500, verbose_name='etykieta')),
                ('description', models.CharField(max_length=1000, verbose_name='wartość')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DefinitionList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('term_label', models.CharField(blank=True, max_length=100, verbose_name='nagłówek etykiet')),
                ('description_label', models.CharField(blank=True, max_length=100, verbose_name='nagłówek wartości')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('url', models.URLField(help_text='Adres filmu na YouTube albo Vimeo, np. https://www.youtube.com/watch?v=…', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='adres filmu')),
                ('title', models.CharField(help_text='Czytany przez czytniki ekranu zamiast zawartości ramki.', max_length=200, verbose_name='tytuł filmu')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('section', models.CharField(blank=True, help_text='Nagłówek grupy, np. „Konto i rejestracja”. Puste = pytanie bez sekcji.', max_length=100, verbose_name='sekcja')),
                ('question', models.CharField(max_length=250, verbose_name='pytanie')),
                ('answer', djangocms_text.fields.HTMLField(verbose_name='odpowiedź')),
                ('anchor', models.CharField(blank=True, help_text='Fragment adresu po „#”. Puste = nadawana automatycznie i potem stała.', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='kotwica')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(max_length=250, verbose_name='tekst')),
                ('level', models.CharField(choices=[('2', 'rozdział (H2)'), ('3', 'paragraf (H3)')], default='2', max_length=1, verbose_name='poziom')),
                ('anchor', models.CharField(help_text='Fragment adresu po „#”, np. „rozdzial-3”. Zmiana psuje istniejące odnośniki.', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='kotwica')),
                ('in_toc', models.BooleanField(default=True, verbose_name='pokaż w spisie rozdziałów')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, help_text='Puste = tytuł strony.', max_length=200, verbose_name='hasło')),
                ('text', djangocms_text.fields.HTMLField(blank=True, verbose_name='tekst pod hasłem')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('tone', models.CharField(choices=[('info', 'informacja'), ('warning', 'ostrzeżenie')], default='info', max_length=10, verbose_name='ton')),
                ('text', djangocms_text.fields.HTMLField(verbose_name='treść')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='podpis tabeli')),
                ('topic_label', models.CharField(blank=True, max_length=100, verbose_name='nagłówek kolumny „temat”')),
                ('date_label', models.CharField(blank=True, max_length=100, verbose_name='nagłówek kolumny „termin”')),
                ('time_label', models.CharField(blank=True, max_length=100, verbose_name='nagłówek kolumny „godziny”')),
                ('lecturer_label', models.CharField(blank=True, max_length=100, verbose_name='nagłówek kolumny „prowadzący”')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ScheduleRow',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('topic', models.CharField(max_length=250, verbose_name='temat')),
                ('date', models.CharField(max_length=100, verbose_name='termin')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='termin (data)')),
                ('time', models.CharField(blank=True, max_length=100, verbose_name='godziny')),
                ('lecturer', models.CharField(blank=True, max_length=200, verbose_name='prowadzący')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=120, verbose_name='tytuł kroku')),
                ('text', models.TextField(max_length=300, verbose_name='opis')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='StepsSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='nagłówek sekcji')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('url', models.URLField(blank=True, help_text='Np. dokument na stronie głównej olimpiady (https://…/documents/5/regulamin.pdf).', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='adres pliku')),
                ('extension', models.CharField(blank=True, help_text='Np. „pdf”. Przy pliku z biblioteki uzupełnia się samo; przy adresie – z końcówki adresu.', max_length=10, verbose_name='rozszerzenie')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, help_text='Przy pliku z biblioteki uzupełnia się samo. Puste = rozmiar nie jest pokazywany.', null=True, verbose_name='rozmiar (bajty)')),
                ('kind', models.CharField(choices=[('PROBLEMS', 'zadania'), ('SOLUTIONS', 'rozwiązania'), ('OTHER', 'inne')], default='PROBLEMS', max_length=16, verbose_name='rodzaj')),
                ('title', models.CharField(max_length=200, verbose_name='etykieta')),
                ('file', filer.fields.file.FilerFileField(blank=True, help_text='Plik wgrany do biblioteki dj. Wypełnij to pole albo adres – nie oba.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='filer.file', verbose_name='plik z biblioteki')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('url', models.URLField(blank=True, help_text='Np. dokument na stronie głównej olimpiady (https://…/documents/5/regulamin.pdf).', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='adres pliku')),
                ('extension', models.CharField(blank=True, help_text='Np. „pdf”. Przy pliku z biblioteki uzupełnia się samo; przy adresie – z końcówki adresu.', max_length=10, verbose_name='rozszerzenie')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, help_text='Przy pliku z biblioteki uzupełnia się samo. Puste = rozmiar nie jest pokazywany.', null=True, verbose_name='rozmiar (bajty)')),
                ('label', models.CharField(blank=True, help_text='Rola pliku, np. „PDF do druku”. Puste = tytuł pliku.', max_length=100, verbose_name='etykieta')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='tytuł pliku')),
                ('file', filer.fields.file.FilerFileField(blank=True, help_text='Plik wgrany do biblioteki dj. Wypełnij to pole albo adres – nie oba.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='filer.file', verbose_name='plik z biblioteki')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('url', models.URLField(blank=True, help_text='Np. dokument na stronie głównej olimpiady (https://…/documents/5/regulamin.pdf).', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='adres pliku')),
                ('extension', models.CharField(blank=True, help_text='Np. „pdf”. Przy pliku z biblioteki uzupełnia się samo; przy adresie – z końcówki adresu.', max_length=10, verbose_name='rozszerzenie')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, help_text='Przy pliku z biblioteki uzupełnia się samo. Puste = rozmiar nie jest pokazywany.', null=True, verbose_name='rozmiar (bajty)')),
                ('label', models.CharField(blank=True, help_text='Puste = tytuł pliku.', max_length=250, verbose_name='etykieta linku')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='tytuł pliku')),
                ('file', filer.fields.file.FilerFileField(blank=True, help_text='Plik wgrany do biblioteki dj. Wypełnij to pole albo adres – nie oba.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='filer.file', verbose_name='plik z biblioteki')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ImageWithCaption',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='podpis')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='obraz')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('level', models.CharField(choices=[('patron-honorowy', 'patron honorowy'), ('partner-instytucjonalny', 'partner instytucjonalny'), ('partner-naukowy', 'partner naukowy'), ('sponsor-diamentowy', 'sponsor diamentowy'), ('sponsor-platynowy', 'sponsor platynowy'), ('sponsor-zloty', 'sponsor złoty'), ('partner-medialny', 'partner medialny')], default='partner-instytucjonalny', help_text='Decyduje o grupie, w której partner stoi na stronie.', max_length=40, verbose_name='poziom współpracy')),
                ('url', models.URLField(blank=True, max_length=300, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='strona partnera')),
                ('description', models.CharField(blank=True, help_text='Jedno zdanie: na czym polega współpraca.', max_length=300, verbose_name='opis')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='logotyp')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
