# Generated by Django 6.1.1 on 2026-10-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenderDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True, verbose_name='domena')),
                ('verified', models.BooleanField(default=False, verbose_name='zweryfikowana')),
                ('checked_at', models.DateTimeField(verbose_name='ostatnie sprawdzenie')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatnia udana weryfikacja')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='raport')),
            ],
            options={
                'verbose_name': 'domena nadawcy',
                'verbose_name_plural': 'domeny nadawców',
                'ordering': ['domain'],
            },
        ),
    ]
