# Generated by Django 5.1.15 on 2026-09-17 12:30

import apps.integrations.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0018_alter_stage_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='adres')),
                ('secret', models.CharField(default=apps.integrations.models.generate_secret, max_length=64, verbose_name='sekret podpisu')),
                ('events', models.JSONField(blank=True, default=apps.integrations.models.default_events, verbose_name='zdarzenia')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dodany')),
                ('failures', models.PositiveIntegerField(default=0, verbose_name='porażki pod rząd')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='wygaszony')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL, verbose_name='dodał')),
                ('edition', models.ForeignKey(blank=True, help_text='Puste = odbiorca dostaje zdarzenia ze wszystkich edycji.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='competitions.edition', verbose_name='edycja')),
            ],
            options={
                'verbose_name': 'odbiorca webhooków',
                'verbose_name_plural': 'odbiorcy webhooków',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dla kogo jest ten klucz.', max_length=120, verbose_name='nazwa')),
                ('prefix', models.CharField(default=apps.integrations.models.generate_prefix, max_length=8, unique=True, verbose_name='przedrostek')),
                ('key_hash', models.CharField(editable=False, max_length=64, verbose_name='skrót klucza')),
                ('scopes', models.JSONField(blank=True, default=apps.integrations.models.default_scopes, verbose_name='zakresy')),
                ('pii_allowed', models.BooleanField(default=False, help_text='Warunek konieczny dla zakresu read:participants_pii.', verbose_name='dane osobowe dozwolone')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=120, verbose_name='limit żądań na minutę')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='wystawiony')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatnio użyty')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='unieważniony')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='wystawił')),
                ('edition', models.ForeignKey(blank=True, help_text='Puste = klucz widzi wszystkie edycje.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='competitions.edition', verbose_name='edycja')),
            ],
            options={
                'verbose_name': 'klucz API',
                'verbose_name_plural': 'klucze API',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('rate_limit_per_minute__gte', 1), ('rate_limit_per_minute__lte', 6000)), name='integrations_apikey_rate_limit_range')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40, verbose_name='zdarzenie')),
                ('payload', models.JSONField(blank=True, default=apps.integrations.models.default_payload, verbose_name='ładunek')),
                ('status', models.CharField(choices=[('PENDING', 'w kolejce'), ('DELIVERED', 'doręczone'), ('FAILED', 'nieudane')], default='PENDING', max_length=16, verbose_name='stan')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='liczba prób')),
                ('last_error', models.CharField(blank=True, max_length=300, verbose_name='ostatni błąd')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='utworzone')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='doręczone')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint', verbose_name='odbiorca')),
            ],
            options={
                'verbose_name': 'doręczenie webhooka',
                'verbose_name_plural': 'doręczenia webhooków',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['endpoint', '-created_at'], name='integrations_delivery_idx')],
            },
        ),
    ]
