# Generated by Django 6.1.1 on 2026-10-04 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0033_video_room'),
        ('submissions', '0008_submissionfile_forwarded_at'),
        ('tenancy', '0012_competition_site_logo_social_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('FREE', 'Notatnik swobodny (ocenia komisja)'), ('AUTOGRADED', 'Sprawdzanie automatyczne (testy)')], default='FREE', max_length=12, verbose_name='tryb')),
                ('language', models.CharField(choices=[('pl', 'polski'), ('en', 'English')], default='pl', max_length=2, verbose_name='język treści notatnika')),
                ('starter_notebook', models.JSONField(blank=True, null=True, verbose_name='notatnik startowy')),
                ('visible_tests', models.JSONField(blank=True, default=list, verbose_name='testy widoczne')),
                ('hidden_tests', models.JSONField(blank=True, default=list, verbose_name='testy ukryte')),
                ('reference_notebook', models.JSONField(blank=True, null=True, verbose_name='notatnik wzorcowy')),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=20, verbose_name='limit czasu (s)')),
                ('memory_limit_mb', models.PositiveSmallIntegerField(default=512, verbose_name='limit pamięci (MB)')),
                ('results_visibility', models.CharField(choices=[('STAFF', 'Tylko organizator i komisja'), ('AFTER_CLOSE', 'Uczestnik po zamknięciu etapu'), ('IMMEDIATE', 'Uczestnik od razu (zalecane tylko na etapach treningowych)')], default='STAFF', max_length=12, verbose_name='widoczność wyników testów ukrytych')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_task', to='competitions.problem', verbose_name='zadanie')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notatnik zadania',
                'verbose_name_plural': 'notatniki zadań',
            },
        ),
        migrations.CreateModel(
            name='NotebookRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reference', models.BooleanField(default=False)),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'w kolejce'), ('RUNNING', 'sprawdzanie'), ('DONE', 'sprawdzono'), ('ERROR', 'błąd sprawdzania'), ('SUPERSEDED', 'zastąpiony nowszą wersją')], db_index=True, default='PENDING', max_length=12)),
                ('results', models.JSONField(blank=True, default=list)),
                ('visible_results', models.JSONField(blank=True, default=list)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('cell_errors', models.JSONField(blank=True, default=list)),
                ('output_tail', models.TextField(blank=True)),
                ('tests_hash', models.CharField(blank=True, max_length=64)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.competition')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebook_runs', to='submissions.submission')),
                ('submission_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='submissions.submissionfile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='notebooks.notebooktask')),
            ],
            options={
                'verbose_name': 'przebieg oceny notatnika',
                'verbose_name_plural': 'przebiegi oceny notatników',
                'ordering': ('-requested_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='notebooktask',
            constraint=models.CheckConstraint(condition=models.Q(('time_limit_seconds__gte', 5), ('time_limit_seconds__lte', 60)), name='notebooks_task_time_limit_range'),
        ),
        migrations.AddConstraint(
            model_name='notebooktask',
            constraint=models.CheckConstraint(condition=models.Q(('memory_limit_mb__gte', 256), ('memory_limit_mb__lte', 1024)), name='notebooks_task_memory_limit_range'),
        ),
        migrations.AddIndex(
            model_name='notebookrun',
            index=models.Index(fields=['task', 'status'], name='notebooks_run_task_status'),
        ),
        migrations.AddConstraint(
            model_name='notebookrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', False)), fields=('submission_file',), name='notebooks_run_unique_file'),
        ),
    ]
