# Generated by Django 6.1.1 on 2026-09-30 21:44

import apps.chat.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0034_clear_anonymised_profile_data'),
        ('tenancy', '0010_path_prefix_routing_on_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(verbose_name='klucz publiczny (SPKI, base64)')),
                ('wrapped_private_key', models.TextField(verbose_name='klucz prywatny zaszyfrowany hasłem (base64)')),
                ('kdf_salt', models.CharField(max_length=64, verbose_name='sól PBKDF2 (base64)')),
                ('wrap_iv', models.CharField(max_length=32, verbose_name='IV owinięcia (base64)')),
                ('kdf_iterations', models.PositiveIntegerField(verbose_name='iteracje PBKDF2')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='odcisk klucza (SHA-256, hex)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_key', to='accounts.participant', verbose_name='uczestnik')),
            ],
            options={
                'verbose_name': 'klucz szyfrowania wiadomości',
                'verbose_name_plural': 'klucze szyfrowania wiadomości',
            },
        ),
        migrations.CreateModel(
            name='ChatNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_message', models.BooleanField(default=True, verbose_name='list o nowej wiadomości')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmienione')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='konto')),
            ],
            options={
                'verbose_name': 'ustawienia powiadomień o wiadomościach',
                'verbose_name_plural': 'ustawienia powiadomień o wiadomościach',
            },
        ),
        migrations.CreateModel(
            name='ChatProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discoverable', models.BooleanField(default=False, verbose_name='widoczny w katalogu')),
                ('token', models.CharField(default=apps.chat.models.new_profile_token, max_length=32, unique=True, verbose_name='identyfikator w katalogu')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmienione')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to='accounts.participant', verbose_name='uczestnik')),
            ],
            options={
                'verbose_name': 'profil wiadomości',
                'verbose_name_plural': 'profile wiadomości',
            },
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Wiadomości włączone')),
                ('peer_mode', models.CharField(choices=[('OFF', 'wyłączone'), ('PRE', 'premoderacja'), ('POST', 'postmoderacja'), ('NONE', 'bez moderacji')], default='OFF', max_length=8, verbose_name='rozmowy między uczestnikami')),
                ('e2e_enabled', models.BooleanField(default=False, verbose_name='szyfrowanie end-to-end')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmienione')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='tenancy.competition', verbose_name='konkurs')),
            ],
            options={
                'verbose_name': 'ustawienia wiadomości',
                'verbose_name_plural': 'ustawienia wiadomości',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ORGANIZER', 'z organizatorem'), ('PEER', 'między uczestnikami')], max_length=10, verbose_name='rodzaj')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='szyfrowana end-to-end')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='rozpoczęta')),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ostatnia wiadomość')),
                ('organizer_unread_since', models.DateTimeField(blank=True, null=True, verbose_name='nieprzeczytane od (organizator)')),
                ('organizer_last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatni odczyt (organizator)')),
                ('organizer_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatni list (organizator)')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='tenancy.competition', verbose_name='konkurs')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_organizer_conversations', to='accounts.participant', verbose_name='uczestnik (rozmowa z organizatorem)')),
                ('participant_high', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.participant', verbose_name='uczestnik B')),
                ('participant_low', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.participant', verbose_name='uczestnik A')),
            ],
            options={
                'verbose_name': 'rozmowa',
                'verbose_name_plural': 'rozmowy',
                'ordering': ('-last_message_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='od')),
                ('unread_since', models.DateTimeField(blank=True, null=True, verbose_name='nieprzeczytane od')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatni odczyt')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatni list')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.conversation', verbose_name='rozmowa')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to='accounts.participant', verbose_name='uczestnik')),
            ],
            options={
                'verbose_name': 'strona rozmowy',
                'verbose_name_plural': 'strony rozmów',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('PARTICIPANT', 'uczestnik'), ('ORGANIZER', 'organizator')], max_length=12, verbose_name='strona nadawcy')),
                ('body', models.TextField(blank=True, max_length=4000, verbose_name='treść')),
                ('ciphertext', models.TextField(blank=True, verbose_name='szyfrogram')),
                ('iv', models.CharField(blank=True, max_length=32, verbose_name='IV szyfrogramu')),
                ('sender_public_key', models.TextField(blank=True, verbose_name='klucz publiczny nadawcy')),
                ('recipient_public_key', models.TextField(blank=True, verbose_name='klucz publiczny odbiorcy')),
                ('status', models.CharField(choices=[('PENDING', 'czeka na akceptację'), ('PUBLISHED', 'doręczona'), ('REJECTED', 'odrzucona'), ('HIDDEN', 'ukryta przez moderatora')], default='PUBLISHED', max_length=10, verbose_name='stan')),
                ('moderation_mode', models.CharField(blank=True, choices=[('OFF', 'wyłączone'), ('PRE', 'premoderacja'), ('POST', 'postmoderacja'), ('NONE', 'bez moderacji')], max_length=8, verbose_name='tryb w chwili wysłania')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='wysłana')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='moderowana')),
                ('moderation_note', models.CharField(blank=True, max_length=500, verbose_name='notatka moderatora')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='przejrzana')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='rozmowa')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_moderated_messages', to=settings.AUTH_USER_MODEL, verbose_name='moderował')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='nadawca')),
            ],
            options={
                'verbose_name': 'wiadomość',
                'verbose_name_plural': 'wiadomości',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='powód')),
                ('reported_plaintext', models.TextField(blank=True, max_length=4000, verbose_name='treść przekazana przez zgłaszającego')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zgłoszone')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='rozpatrzone')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message', verbose_name='wiadomość')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports', to=settings.AUTH_USER_MODEL, verbose_name='zgłaszający')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_resolved_reports', to=settings.AUTH_USER_MODEL, verbose_name='rozpatrzył')),
            ],
            options={
                'verbose_name': 'zgłoszenie wiadomości',
                'verbose_name_plural': 'zgłoszenia wiadomości',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='od')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks_received', to='accounts.participant', verbose_name='zablokowany')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks_made', to='accounts.participant', verbose_name='blokujący')),
            ],
            options={
                'verbose_name': 'blokada',
                'verbose_name_plural': 'blokady',
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='chat_block_once'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='chat_block_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['competition', 'kind', '-last_message_at'], name='chat_conversation_list_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'ORGANIZER')), fields=('competition', 'participant'), name='chat_one_organizer_conversation_per_participant'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'PEER')), fields=('participant_low', 'participant_high'), name='chat_one_peer_conversation_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'ORGANIZER'), ('participant_high__isnull', True), ('participant_low__isnull', True)), models.Q(('kind', 'PEER'), ('participant__isnull', True), models.Q(('participant_low__isnull', True), ('participant_high__isnull', True), ('participant_low__lt', models.F('participant_high')), _connector='OR')), _connector='OR'), name='chat_conversation_shape'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'PEER'), ('is_encrypted', False), _connector='OR'), name='chat_organizer_never_encrypted'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['participant', 'unread_since'], name='chat_member_unread_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.UniqueConstraint(fields=('conversation', 'participant'), name='chat_member_once'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_message_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'moderation_mode', 'reviewed_at'], name='chat_message_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='chat_message_sender_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ciphertext', ''), ('iv', ''), models.Q(('body', ''), _negated=True)), models.Q(('body', ''), models.Q(('ciphertext', ''), _negated=True), models.Q(('iv', ''), _negated=True)), _connector='OR'), name='chat_message_body_or_ciphertext'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(fields=('message', 'reporter'), name='chat_report_once'),
        ),
    ]
