# Generated by Django 6.1.1 on 2026-09-30 23:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_clear_anonymised_profile_data'),
        ('chat', '0001_initial'),
        ('tenancy', '0010_path_prefix_routing_on_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='nazwa')),
                ('body', models.TextField(max_length=4000, verbose_name='treść')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmieniony')),
            ],
            options={
                'verbose_name': 'szablon odpowiedzi',
                'verbose_name_plural': 'szablony odpowiedzi',
                'ordering': ('title', 'id'),
            },
        ),
        migrations.AddField(
            model_name='chatsettings',
            name='age_policy',
            field=models.CharField(choices=[('SAME_GROUP', 'tylko w tej samej grupie wiekowej'), ('ANY', 'bez ograniczeń wieku')], default='SAME_GROUP', max_length=12, verbose_name='grupa wiekowa w rozmowach uczestników'),
        ),
        migrations.AddField(
            model_name='chatsettings',
            name='daily_new_conversations',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='nowe rozmowy uczestnika na dobę'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='przypisana do'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.participant', verbose_name='rozpoczął'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'otwarta'), ('WAITING', 'czeka na uczestnika'), ('CLOSED', 'zamknięta')], default='OPEN', max_length=8, verbose_name='stan (skrzynka organizatora)'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='stan zmieniony'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['started_by', 'created_at'], name='chat_conversation_started_idx'),
        ),
        migrations.AddField(
            model_name='replytemplate',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reply_templates', to='tenancy.competition', verbose_name='konkurs'),
        ),
        migrations.AddField(
            model_name='replytemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
    ]
