# Generated by Django 6.1.1 on 2026-09-24 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0008_competition_submission_forward_emails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_key', models.CharField(max_length=120, verbose_name='warsztat (klucz)')),
                ('workshop_topic', models.CharField(blank=True, max_length=300, verbose_name='temat warsztatu (migawka)')),
                ('workshop_date', models.DateField(blank=True, null=True, verbose_name='data warsztatu (migawka)')),
                ('kind', models.CharField(choices=[('video', 'film'), ('file', 'plik'), ('link', 'odnośnik')], max_length=10, verbose_name='rodzaj')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='opis')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='adres')),
                ('object_key', models.CharField(blank=True, max_length=255, verbose_name='klucz obiektu')),
                ('upload_id', models.CharField(blank=True, max_length=255, verbose_name='identyfikator wgrywania')),
                ('file_format', models.CharField(blank=True, max_length=10, verbose_name='format')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='rozmiar (B)')),
                ('status', models.CharField(choices=[('uploading', 'wgrywanie'), ('scanning', 'sprawdzanie antywirusowe'), ('ready', 'gotowy'), ('rejected', 'odrzucony')], default='uploading', max_length=12, verbose_name='stan')),
                ('status_note', models.CharField(blank=True, max_length=300, verbose_name='uwaga')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
                ('is_published', models.BooleanField(default=False, verbose_name='opublikowany')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='wyświetlenia')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniony')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='gotowy od')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_materials', to='tenancy.competition', verbose_name='konkurs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='dodał')),
            ],
            options={
                'verbose_name': 'materiał z warsztatów',
                'verbose_name_plural': 'materiały z warsztatów',
                'ordering': ('competition', 'workshop_key', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkshopMaterialViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_hash', models.CharField(max_length=64, verbose_name='pseudonim widza')),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='pierwsze wyświetlenie')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='workshop_materials.workshopmaterial', verbose_name='materiał')),
            ],
            options={
                'verbose_name': 'widz materiału',
                'verbose_name_plural': 'widzowie materiałów',
            },
        ),
        migrations.AddIndex(
            model_name='workshopmaterial',
            index=models.Index(fields=['competition', 'workshop_key', 'position'], name='workshop_material_listing'),
        ),
        migrations.AddIndex(
            model_name='workshopmaterial',
            index=models.Index(fields=['status', 'created_at'], name='workshop_material_status'),
        ),
        migrations.AddConstraint(
            model_name='workshopmaterialviewer',
            constraint=models.UniqueConstraint(fields=('material', 'viewer_hash'), name='workshop_material_viewer_unique'),
        ),
    ]
