# Generated by Django 6.1.1 on 2026-09-21 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0008_competition_submission_forward_emails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nazwa')),
                ('slug', models.SlugField(max_length=60, verbose_name='identyfikator')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='opis')),
                ('ordering', models.PositiveSmallIntegerField(default=100, verbose_name='kolejność')),
                ('is_open', models.BooleanField(default=True, verbose_name='otwarty na nowe wątki')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_categories', to='tenancy.competition', verbose_name='konkurs')),
            ],
            options={
                'verbose_name': 'kategoria forum',
                'verbose_name_plural': 'kategorie forum',
                'ordering': ('ordering', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=5000, verbose_name='treść')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dodany')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='poprawiony')),
                ('status', models.CharField(choices=[('PENDING', 'czeka na moderację'), ('PUBLISHED', 'opublikowane'), ('REJECTED', 'odrzucone'), ('HIDDEN', 'ukryte')], default='PENDING', max_length=16, verbose_name='stan')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='moderowany')),
                ('moderation_note', models.CharField(blank=True, max_length=500, verbose_name='uzasadnienie moderatora')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='tenancy.competition', verbose_name='konkurs')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_moderated_posts', to=settings.AUTH_USER_MODEL, verbose_name='moderował')),
            ],
            options={
                'verbose_name': 'wpis forum',
                'verbose_name_plural': 'wpisy forum',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ForumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='powód')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zgłoszone')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='rozpatrzone')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reports', to='tenancy.competition', verbose_name='konkurs')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.forumpost', verbose_name='wpis')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_reports', to=settings.AUTH_USER_MODEL, verbose_name='zgłaszający')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_resolved_reports', to=settings.AUTH_USER_MODEL, verbose_name='rozpatrzył')),
            ],
            options={
                'verbose_name': 'zgłoszenie wpisu',
                'verbose_name_plural': 'zgłoszenia wpisów',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ForumSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('PRE', 'przed publikacją'), ('POST', 'po publikacji')], default='PRE', max_length=8, verbose_name='tryb moderacji')),
                ('is_read_only', models.BooleanField(default=False, verbose_name='tylko do odczytu')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zmienione')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_settings', to='tenancy.competition', verbose_name='konkurs')),
            ],
            options={
                'verbose_name': 'ustawienia forum',
                'verbose_name_plural': 'ustawienia forum',
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='temat')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='założony')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ostatnia aktywność')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='przypięty')),
                ('is_locked', models.BooleanField(default=False, verbose_name='zamknięty')),
                ('status', models.CharField(choices=[('PENDING', 'czeka na moderację'), ('PUBLISHED', 'opublikowane'), ('REJECTED', 'odrzucone'), ('HIDDEN', 'ukryte')], default='PENDING', max_length=16, verbose_name='stan')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='moderowany')),
                ('moderation_note', models.CharField(blank=True, max_length=500, verbose_name='uzasadnienie moderatora')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.forumcategory', verbose_name='kategoria')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='tenancy.competition', verbose_name='konkurs')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_moderated_threads', to=settings.AUTH_USER_MODEL, verbose_name='moderował')),
            ],
            options={
                'verbose_name': 'wątek forum',
                'verbose_name_plural': 'wątki forum',
                'ordering': ('-is_pinned', '-last_activity_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='forumpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.forumthread', verbose_name='wątek'),
        ),
        migrations.AddConstraint(
            model_name='forumcategory',
            constraint=models.UniqueConstraint(fields=('competition', 'slug'), name='forum_category_slug_per_competition'),
        ),
        migrations.AddIndex(
            model_name='forumreport',
            index=models.Index(fields=['competition', 'resolved_at'], name='forum_report_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['category', 'status', '-last_activity_at'], name='forum_thread_list_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['competition', 'status'], name='forum_thread_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['thread', 'status', 'created_at'], name='forum_post_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author', '-created_at'], name='forum_post_author_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['competition', 'status'], name='forum_post_queue_idx'),
        ),
    ]
