# Generated by Django 6.1.1 on 2026-09-24 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('tenancy', '0009_document_kind_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumModerationDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatni list')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_moderation_digest', to='tenancy.competition', verbose_name='konkurs')),
            ],
            options={
                'verbose_name': 'list o kolejce moderacji',
                'verbose_name_plural': 'listy o kolejce moderacji',
            },
        ),
        migrations.CreateModel(
            name='ForumNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('IMMEDIATE', 'na bieżąco'), ('DAILY', 'raz dziennie'), ('NEVER', 'nigdy')], default='IMMEDIATE', max_length=12, verbose_name='listy o obserwowanych wątkach')),
                ('moderation_digest', models.BooleanField(default=True, verbose_name='listy o wpisach czekających na moderację')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmienione')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='konto')),
            ],
            options={
                'verbose_name': 'ustawienia powiadomień forum',
                'verbose_name_plural': 'ustawienia powiadomień forum',
            },
        ),
        migrations.CreateModel(
            name='ForumDecisionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('POST_APPROVED', 'wpis zatwierdzony'), ('POST_REJECTED', 'wpis odrzucony'), ('THREAD_APPROVED', 'wątek zatwierdzony'), ('THREAD_REJECTED', 'wątek odrzucony')], max_length=20, verbose_name='decyzja')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zapisana')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='obsłużona')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_decision_notices', to='tenancy.competition', verbose_name='konkurs')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_notices', to='forum.forumpost', verbose_name='wpis')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_notices', to='forum.forumthread', verbose_name='wątek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_decision_notices', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'decyzja moderatora do powiadomienia',
                'verbose_name_plural': 'decyzje moderatora do powiadomienia',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['competition', 'handled_at'], name='forum_notice_due_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='obserwuje')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='od')),
                ('pending_since', models.DateTimeField(blank=True, null=True, verbose_name='nowości od')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatni list')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_subscriptions', to='tenancy.competition', verbose_name='konkurs')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='forum.forumthread', verbose_name='wątek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='obserwujący')),
            ],
            options={
                'verbose_name': 'obserwowany wątek',
                'verbose_name_plural': 'obserwowane wątki',
                'indexes': [models.Index(fields=['competition', 'pending_since'], name='forum_subscription_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('thread', 'user'), name='forum_subscription_once')],
            },
        ),
    ]
