# Generated by Django 6.1.1 on 2026-10-04 17:17

import apps.tenancy.fees
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0037_team_leader_rbac_group'),
        ('competitions', '0033_video_room'),
        ('tenancy', '0013_competition_registration_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(max_length=24, unique=True, verbose_name='kod referencyjny')),
                ('currency', models.CharField(max_length=3, validators=[apps.tenancy.fees.validate_currency], verbose_name='waluta')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='suma')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='zwrócono')),
                ('period', models.CharField(blank=True, choices=[('EARLY', 'cena wczesna'), ('REGULAR', 'cena podstawowa'), ('LATE', 'cena późna')], max_length=8, verbose_name='okres cenowy')),
                ('status', models.CharField(choices=[('OPEN', 'czeka na wpłatę'), ('PAID', 'zapłacone'), ('CANCELLED', 'anulowane'), ('REFUNDED', 'zwrócone')], default='OPEN', max_length=10, verbose_name='stan')),
                ('buyer_type', models.CharField(choices=[('INSTITUTION', 'Instytucja'), ('PERSON', 'Osoba prywatna')], max_length=12)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_address', models.TextField(blank=True, max_length=500)),
                ('buyer_country', models.CharField(blank=True, max_length=100)),
                ('buyer_vat_id', models.CharField(blank=True, max_length=32)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('language', models.CharField(default='en', max_length=8, verbose_name='język')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='wystawiono')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='termin płatności')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='zapłacono')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='anulowano')),
                ('cancel_reason', models.CharField(blank=True, max_length=300, verbose_name='powód anulowania')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='tenancy.competition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='accounts.delegation')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.edition')),
                ('participant_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='tenancy.participantfee')),
            ],
            options={
                'verbose_name': 'zamówienie',
                'verbose_name_plural': 'zamówienia',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BillingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PROFORMA', 'Faktura pro forma'), ('INVOICE', 'Faktura')], max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('sequence', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=64, verbose_name='numer')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='wystawiono')),
                ('language', models.CharField(max_length=8)),
                ('snapshot', models.JSONField(default=dict)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.competition')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='payments.order')),
            ],
            options={
                'verbose_name': 'dokument rozliczeniowy',
                'verbose_name_plural': 'dokumenty rozliczeniowe',
                'ordering': ('-issued_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('DELEGATION', 'Opłata za delegację'), ('STUDENT', 'Uczeń'), ('LEADER', 'Opiekun drużyny'), ('OBSERVER', 'Obserwator'), ('PARTICIPANT', 'Opłata za udział'), ('DISCOUNT', 'Zniżka')], max_length=16)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.order')),
            ],
            options={
                'ordering': ('order', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('stripe', 'Karta płatnicza (Stripe)'), ('przelewy24', 'Przelewy24'), ('bank_transfer', 'Przelew bankowy')], max_length=16, verbose_name='dostawca')),
                ('status', models.CharField(choices=[('PENDING', 'w toku'), ('SUCCEEDED', 'przyjęta'), ('FAILED', 'nieudana'), ('CANCELLED', 'przerwana'), ('MISMATCH', 'do wyjaśnienia')], default='PENDING', max_length=10, verbose_name='stan')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kwota')),
                ('currency', models.CharField(max_length=3, verbose_name='waluta')),
                ('provider_ref', models.CharField(blank=True, max_length=255, verbose_name='identyfikator sesji')),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, verbose_name='identyfikator transakcji')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='zwrócono')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzono')),
                ('succeeded_at', models.DateTimeField(blank=True, null=True, verbose_name='przyjęto')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='zamknięto')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='szczegóły')),
                ('received_on', models.DateField(blank=True, null=True, verbose_name='data wpływu')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='notatka')),
                ('proof_key', models.CharField(blank=True, max_length=300, verbose_name='dowód wpłaty (klucz)')),
                ('proof_mime', models.CharField(blank=True, max_length=40)),
                ('proof_size', models.PositiveIntegerField(default=0)),
                ('proof_sha256', models.CharField(blank=True, max_length=64)),
                ('proof_scan_status', models.CharField(blank=True, choices=[('PENDING', 'oczekuje na skan'), ('CLEAN', 'czysty'), ('INFECTED', 'zainfekowany'), ('ERROR', 'błąd skanu')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.order')),
            ],
            options={
                'verbose_name': 'wpłata',
                'verbose_name_plural': 'wpłaty',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_tax_id', models.CharField(blank=True, max_length=32, verbose_name='NIP / VAT ID sprzedawcy')),
                ('bank_account', models.CharField(blank=True, max_length=64, verbose_name='rachunek bankowy (IBAN)')),
                ('bank_swift', models.CharField(blank=True, max_length=11, verbose_name='SWIFT/BIC')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='bank')),
                ('document_prefix', models.CharField(blank=True, help_text='Puste = identyfikator konkursu wielkimi literami, np. IQO/FV/2026/0001.', max_length=12, verbose_name='prefiks numeracji dokumentów')),
                ('vat_note', models.CharField(blank=True, help_text='Np. podstawa zwolnienia albo „odwrotne obciążenie”. System nie liczy podatku.', max_length=300, verbose_name='adnotacja VAT')),
                ('invoice_note', models.TextField(blank=True, max_length=1000, verbose_name='uwagi na dokumentach')),
                ('proforma_due_days', models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='termin płatności pro formy (dni)')),
                ('card_payments', models.BooleanField(default=True, verbose_name='płatność kartą (Stripe)')),
                ('p24_payments', models.BooleanField(default=True, verbose_name='Przelewy24 (tylko PLN)')),
                ('bank_transfer', models.BooleanField(default=True, verbose_name='przelew tradycyjny')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='tenancy.competition', verbose_name='konkurs')),
            ],
            options={
                'verbose_name': 'ustawienia płatności',
                'verbose_name_plural': 'ustawienia płatności',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EUR', max_length=3, validators=[apps.tenancy.fees.validate_currency], verbose_name='waluta')),
                ('early_until', models.DateField(blank=True, null=True, verbose_name='cena wczesna do (włącznie)')),
                ('late_from', models.DateField(blank=True, null=True, verbose_name='cena późna od')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzony')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='tenancy.competition', verbose_name='konkurs')),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='competitions.edition', verbose_name='edycja')),
            ],
            options={
                'verbose_name': 'cennik delegacji',
                'verbose_name_plural': 'cenniki delegacji',
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DELEGATION', 'Opłata za delegację'), ('STUDENT', 'Uczeń'), ('LEADER', 'Opiekun drużyny'), ('OBSERVER', 'Obserwator'), ('PARTICIPANT', 'Opłata za udział'), ('DISCOUNT', 'Zniżka')], max_length=16, verbose_name='pozycja')),
                ('period', models.CharField(choices=[('EARLY', 'cena wczesna'), ('REGULAR', 'cena podstawowa'), ('LATE', 'cena późna')], max_length=8, verbose_name='okres')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kwota')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.pricelist')),
            ],
            options={
                'verbose_name': 'cena',
                'verbose_name_plural': 'ceny',
            },
        ),
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Karta płatnicza (Stripe)'), ('przelewy24', 'Przelewy24'), ('bank_transfer', 'Przelew bankowy')], max_length=16)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('payload_hash', models.CharField(max_length=64)),
                ('outcome', models.CharField(blank=True, max_length=40)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='payments.payment')),
            ],
            options={
                'verbose_name': 'doręczenie od dostawcy',
                'verbose_name_plural': 'doręczenia od dostawców',
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kwota')),
                ('reason', models.CharField(max_length=300, verbose_name='powód')),
                ('status', models.CharField(choices=[('PENDING', 'w toku'), ('SUCCEEDED', 'wykonany'), ('FAILED', 'nieudany')], default='PENDING', max_length=10, verbose_name='stan')),
                ('provider_refund_id', models.CharField(blank=True, max_length=255, verbose_name='identyfikator zwrotu')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='szczegóły')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='zlecono')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='zakończono')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'verbose_name': 'zwrot',
                'verbose_name_plural': 'zwroty',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_type', models.CharField(choices=[('INSTITUTION', 'Instytucja'), ('PERSON', 'Osoba prywatna')], default='INSTITUTION', max_length=12, verbose_name='nabywca')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='nazwa nabywcy')),
                ('buyer_address', models.TextField(max_length=500, verbose_name='adres')),
                ('buyer_country', models.CharField(max_length=100, verbose_name='kraj')),
                ('buyer_vat_id', models.CharField(blank=True, max_length=32, verbose_name='NIP / VAT ID')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='e-mail do rozliczeń')),
                ('observers', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='obserwatorzy')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
                ('delegation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='accounts.delegation', verbose_name='delegacja')),
                ('participant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='accounts.participant', verbose_name='uczestnik')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dane nabywcy',
                'verbose_name_plural': 'dane nabywców',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('delegation__isnull', False), ('participant__isnull', True)), models.Q(('delegation__isnull', True), ('participant__isnull', False)), _connector='OR'), name='payments_billingprofile_one_owner')],
            },
        ),
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PROFORMA', 'Faktura pro forma'), ('INVOICE', 'Faktura')], max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('last', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.competition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('competition', 'kind', 'year'), name='payments_counter_unique')],
            },
        ),
        migrations.CreateModel(
            name='FeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DISCOUNT', 'Zniżka'), ('WAIVER', 'Zwolnienie z opłat')], max_length=10, verbose_name='rodzaj')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='kwota zniżki')),
                ('reason', models.CharField(max_length=300, verbose_name='uzasadnienie')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzono')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='cofnięto')),
                ('revoke_reason', models.CharField(blank=True, max_length=300, verbose_name='powód cofnięcia')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_adjustments', to='tenancy.competition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_adjustments', to='accounts.delegation')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'zniżka / zwolnienie',
                'verbose_name_plural': 'zniżki i zwolnienia',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('kind', 'WAIVER'), ('amount__gt', 0), _connector='OR'), name='payments_adjustment_discount_positive'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='payments_adjustment_has_reason')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['competition', 'edition', 'status'], name='payments_order_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delegation__isnull', False), ('participant_fee__isnull', True)), models.Q(('delegation__isnull', True), ('participant_fee__isnull', False)), _connector='OR'), name='payments_order_one_payer'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='payments_order_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0), ('refunded_amount__lte', models.F('total'))), name='payments_order_refund_within_total'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAID'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='payments_order_paid_has_date'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('participant_fee',), name='payments_order_one_open_per_fee'),
        ),
        migrations.AddConstraint(
            model_name='billingdocument',
            constraint=models.UniqueConstraint(fields=('competition', 'kind', 'year', 'sequence'), name='payments_document_number'),
        ),
        migrations.AddConstraint(
            model_name='billingdocument',
            constraint=models.UniqueConstraint(fields=('order', 'kind'), name='payments_document_one_per_order'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_ref', ''), _negated=True), fields=('provider', 'provider_ref'), name='payments_payment_unique_provider_ref'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0), ('refunded_amount__lte', models.F('amount'))), name='payments_payment_refund_within_amount'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.CheckConstraint(condition=models.Q(('early_until__isnull', True), ('late_from__isnull', True), ('early_until__lt', models.F('late_from')), _connector='OR'), name='payments_pricelist_early_before_late'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.UniqueConstraint(fields=('price_list', 'kind', 'period'), name='payments_priceitem_unique'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payments_priceitem_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='providerevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='payments_providerevent_unique'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='payments_refund_has_reason'),
        ),
    ]
