# Generated by Django 6.1.1 on 2026-10-04 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='ilość')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kwota')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_lines', to='payments.orderline')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.refund')),
            ],
            options={
                'verbose_name': 'pozycja zwrotu',
                'verbose_name_plural': 'pozycje zwrotów',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='payments_refundline_quantity_positive')],
            },
        ),
    ]
